export type BranchImage = {
  src: string;
  label: string;
  inherited?: boolean;
};

export type VersionEntry = {
  version: string;
  year: string;
  title: string;
  status: "prototype" | "calibration" | "current";
  projection: BranchImage;
  bluray: BranchImage;
  summary: string;
  changes: string[];
  errors: string[];
  discoveries: string[];
  refs: string[];
};

const common = (version: string): BranchImage => ({
  src: `/versions/${version}-main.jpg`,
  label: "当时尚未拆分两条观看链；这里保留同一实验主图",
  inherited: true,
});

export const versions: VersionEntry[] = [
  {
    version: "V4",
    year: "结构原型",
    title: "让清晰度与颗粒属于同一种介质",
    status: "prototype",
    projection: common("v4"),
    bluray: common("v4"),
    summary: "第一次停止在成片上覆盖噪点，改为从虚拟乳剂密度场形成图像，并让MTF和颗粒共同决定细节。",
    changes: ["建立曝光域乳剂原型", "加入通道相关的MTF", "保留逐帧随机结构"],
    errors: ["颗粒半径和观察模糊过大", "更接近8mm/16mm，而不是35mm 5279", "颜色仍主要来自经验矩阵"],
    discoveries: ["粗颗粒必须伴随较低的高频清晰度", "颗粒不是独立贴图，而是画面形成机制的一部分"],
    refs: ["R1", "R2"],
  },
  {
    version: "V5",
    year: "5279定标",
    title: "从“胶片感”转向指定片种",
    status: "prototype",
    projection: common("v5"),
    bluray: common("v5"),
    summary: "开始以Kodak VISION 500T 5279的数据表为约束，不再把所有高速彩色负片视为同一种风格。",
    changes: ["引入5279感色与曲线目标", "建立35mm画幅尺度", "开始区分R/G/B记录"],
    errors: ["高光仍受RAW解码和显示端裁切影响", "暗部颗粒偏彩色电子噪声", "三层乳剂尚未显式建模"],
    discoveries: ["5279的蓝记录颗粒测量显著高于绿、红记录", "片种性格必须由曲线、染料和颗粒共同决定"],
    refs: ["R1"],
  },
  {
    version: "V6",
    year: "RAW高光",
    title: "先救回传感器信息，再谈胶片肩部",
    status: "prototype",
    projection: common("v6"),
    bluray: common("v6"),
    summary: "修正GH7 ProRes RAW的线性解释与高光路径，把摄像机裁切和负片肩部压缩分离。",
    changes: ["保持RAW在线性域", "加入分记录高光肩部", "限制极高曝光的长程红层散射"],
    errors: ["颗粒依旧过猛", "高光光学效应曾被做成通用红光晕", "Panasonic色彩变换还不够严格"],
    discoveries: ["负片高光不是简单soft clip", "rem-jet会显著抑制背面散射，5279不应出现夸张光晕"],
    refs: ["R1", "R2", "R3"],
  },
  {
    version: "V7",
    year: "胶片光学",
    title: "把卤化银、散射与防光晕放进同一条链",
    status: "prototype",
    projection: common("v7"),
    bluray: common("v7"),
    summary: "补入乳剂层散射、防光晕层和局部边缘响应，画面开始从均匀噪声变成密度相关的结构。",
    changes: ["曝光相关颗粒", "受控halation", "颗粒与边缘响应耦合"],
    errors: ["形态仍像被推冲的16mm", "三种速度层只是宏观分段", "黑位和观看条件尚未分离"],
    discoveries: ["暗部、亮部的颗粒差异来自不同速度群体进入显影区间", "清晰度匹配比单纯降低噪点更重要"],
    refs: ["R2", "R3"],
  },
  {
    version: "V8",
    year: "35mm细化",
    title: "从生猛16mm收回到细腻35mm",
    status: "calibration",
    projection: common("v8"),
    bluray: common("v8"),
    summary: "缩小染料云、提高有效位点数量、减弱暗部密度摆幅，让颗粒频率和5279的35mm观感接近。",
    changes: ["颗粒半径降至约0.5–1.3原生像素", "增加有效染料云数量", "减弱暗部彩色分离"],
    errors: ["平均响应仍依赖共享曲线", "扫描和放映还没有各自的物理观察器", "染料遮罩没有光谱化"],
    discoveries: ["细腻并不等于静止：更小、更密的位点仍可产生有机逐帧变化"],
    refs: ["R1", "R2"],
  },
  {
    version: "V9",
    year: "双分支起点",
    title: "5279负片曲线、光谱染料与两种观看结果",
    status: "calibration",
    projection: { src: "/versions/v9-projection.jpg", label: "早期正片解释" },
    bluray: { src: "/versions/v9-bluray.jpg", label: "5279负片扫描解释" },
    summary: "首次分别采样5279红、绿、蓝Status-M曲线，并建立扫描与印片两条观看分支。",
    changes: ["三条独立H-D曲线", "净染料密度的初步光谱模型", "扫描与正片分离"],
    errors: ["正片仍是经验性正值染料矩阵", "未完整保留橙色底和有色耦合剂的负密度瓣", "两条分支的色彩基准不统一"],
    discoveries: ["5279数据表的染料曲线是D-min已扣除的净变化，并非纯染料吸收", "遮罩耦合剂必须只计算一次"],
    refs: ["R1", "R2", "R4"],
  },
  {
    version: "V10",
    year: "2383初版",
    title: "把Kodak 2383作为第二种真实材料",
    status: "calibration",
    projection: { src: "/versions/v10-projection.jpg", label: "5279 → 2383 初版" },
    bluray: { src: "/versions/v9-bluray.jpg", label: "扫描分支沿用V9", inherited: true },
    summary: "加入2383的感光曲线、染料和印片灯，使放映不再是对负片做一条显示LUT。",
    changes: ["第二套H-D曲线", "LAD目标密度", "2383染料与正片颗粒"],
    errors: ["曾把净负密度曲线当成纯正值染料，造成严重紫红偏色", "橙色底被错误去除或重复补偿", "正片陡峭曲线放大了小型光谱误差"],
    discoveries: ["光学印片必须保留5279 D-min/橙色底在光路中", "扫描去底与印片补偿不是同一操作"],
    refs: ["R1", "R3", "R4"],
  },
  {
    version: "V11",
    year: "灰阶校准",
    title: "不只校准18%灰，而是校准整条灰阶",
    status: "calibration",
    projection: { src: "/versions/v11-projection.jpg", label: "2383氙灯放映" },
    bluray: { src: "/versions/v11-bluray.jpg", label: "Cineon / Spirit 2K扫描" },
    summary: "用LAD与多级灰阶约束中性，建立Cineon编码和Spirit式扫描基础。",
    changes: ["多点中性灰校准", "Cineon代码值95/445锚点", "两条分支统一Rec.709输出"],
    errors: ["局部颜色仍由粗糙矩阵修正", "扫描器光谱被近似为Status-M", "蓝光完成阶段黑位尚未单独设计"],
    discoveries: ["中灰中性并不能保证高光和暗部中性", "黑位是观看链决策，不应倒推修改负片D-min"],
    refs: ["R5", "R8"],
  },
  {
    version: "V12",
    year: "有色遮罩",
    title: "保留有色耦合剂的净负密度",
    status: "calibration",
    projection: { src: "/versions/v12-projection.jpg", label: "修正遮罩后的放映" },
    bluray: { src: "/versions/v12-bluray.jpg", label: "修正遮罩后的扫描" },
    summary: "将5279数据表的21点光谱曲线作为带符号的净密度变化，正确解释有色遮罩。",
    changes: ["21波长光谱LUT", "保留小型负密度瓣", "DIR局部邻接初版"],
    errors: ["扫描端仍使用窄带观察器", "DIR在总密度形成后才计算", "色彩分离缺少亚层依赖"],
    discoveries: ["负值不是数据错误，而是遮罩耦合剂被消耗的方向", "平均校正平坦仍会留下片种特有的光谱残差"],
    refs: ["R1", "R2", "R3", "R6"],
  },
  {
    version: "V13",
    year: "投影光源",
    title: "从黑体白光改为电影氙灯光谱",
    status: "calibration",
    projection: { src: "/versions/v13-projection.jpg", label: "修正后的2383氙灯放映" },
    bluray: { src: "/versions/v13-bluray.jpg", label: "Spirit 2K扫描" },
    summary: "加入氙灯的非平滑光谱结构、CIE观察器和投影散射。早期放映版的紫红错误也被明确记录并修正。",
    changes: ["氙灯SPD", "CIE XYZ观察", "Callier/投影散射的保守近似"],
    errors: ["第一版放映严重紫红，根因是打印光谱与染料解释叠加错误", "显示器上观看物理放映结果时，对比和色浓度过强"],
    discoveries: ["“物理投影”与“在显示器上呈现投影质感”需要两个不同目标", "小色相误差会被2383陡峭曲线放大"],
    refs: ["R2", "R4", "R7"],
  },
  {
    version: "V14",
    year: "三速度层",
    title: "有限快／中／慢感光位点",
    status: "calibration",
    projection: { src: "/versions/v14-projection.jpg", label: "多层颗粒放映" },
    bluray: { src: "/versions/v14-bluray.jpg", label: "多层颗粒扫描" },
    summary: "每个颜色记录拥有快、中、慢三组有限位点，以二项统计形成曝光相关颗粒，并严格回标5279的48µm RMS曲线。",
    changes: ["9组有限位点", "p(1−p)方差", "48µm测量孔径校准"],
    errors: ["R/G/B共用一套代表性颗粒尺寸", "每组内部仍是单一圆形尺寸", "颗粒颜色相关性不够有机"],
    discoveries: ["位点接近全显影时方差会再次下降", "‘阴影粗、亮部细’是群体转换，不是简单亮度遮罩"],
    refs: ["R1", "R2", "R7"],
  },
  {
    version: "V15",
    year: "完整印片光路",
    title: "橙色底、印片灯、2383与色域映射",
    status: "calibration",
    projection: { src: "/versions/v15-projection.jpg", label: "完整光谱印片链" },
    bluray: { src: "/versions/v15-bluray.jpg", label: "扫描链校准" },
    summary: "在全波长光路中保留橙色底，用印片灯补偿并通过2383形成正片；加入RGB分离补偿。",
    changes: ["D-min全光谱传输", "印片灯中性补偿", "H-61/TAF式颜色分离校准"],
    errors: ["投影颜色仍偏深、偏蓝", "暗红和绿色曾发生大角度色相旋转", "扫描黑位与颗粒积分顺序仍有问题"],
    discoveries: ["投影浓郁感一部分是2383斜率，另一部分可能是错误观看适配", "色域压缩必须尽量保持恒定色相"],
    refs: ["R3", "R4", "R5"],
  },
  {
    version: "V16",
    year: "观看链校准",
    title: "放映黑、扫描黑与色相稳定",
    status: "calibration",
    projection: { src: "/versions/v16-projection.jpg", label: "典型16 ft-L放映" },
    bluray: { src: "/versions/v16-bluray.jpg", label: "2K DI / 蓝光完成" },
    summary: "分离无杂散光投影、典型影院投影和蓝光完成；用OKLab恒色相压缩修正暗部色偏。",
    changes: ["典型1%投影flare", "OKLab恒色相压缩", "蓝光下段gamma与真实黑锚点"],
    errors: ["蓝光颗粒会在显示黑边界形成单边偏置", "投影在显示器上仍显得过重", "扫描高频彩色颗粒多于参考影片"],
    discoveries: ["投影黑位和蓝光黑位来自不同物理/显示链", "《霹雳娇娃2》只能约束完成态，不能当作未调色5279测量"],
    refs: ["R8", "R9", "R10"],
  },
  {
    version: "V17",
    year: "扫描修正",
    title: "在透射光域完成Spirit 2K积分",
    status: "calibration",
    projection: { src: "/versions/v16-projection.jpg", label: "放映分支沿用V16", inherited: true },
    bluray: { src: "/versions/v17-bluray.jpg", label: "V17透射域扫描" },
    summary: "扫描器先对穿过负片的光做2K面积积分，再转回密度和Cineon，解决黑场被颗粒抬起的问题。",
    changes: ["透射域2K孔径", "显示边界之后才形成", "蓝光高频色度颗粒受控积分"],
    errors: ["物理放映与显示器观看仍未适配", "扫描观察器仍近似Status-M", "颗粒形态还太规则"],
    discoveries: ["扫描器看到的是透射光，不是已经裁到黑的正片RGB", "正确的运算顺序本身就能修复浮黑"],
    refs: ["R8", "R10"],
  },
  {
    version: "V18",
    year: "显示适配",
    title: "区分物理2383投影与显示器上的放映质感",
    status: "calibration",
    projection: { src: "/versions/v18-projection.jpg", label: "2383显示器观看适配" },
    bluray: { src: "/versions/v17-bluray.jpg", label: "蓝光分支沿用V17", inherited: true },
    summary: "保留物理投影分支，同时建立适合Rec.709显示器判断的投影外观；分离GH7传感器噪声和虚拟乳剂颗粒。",
    changes: ["投影monitor分支", "中性灰多锚点适配", "场景线性传感器噪声分离"],
    errors: ["早期适配仍有轻微蓝偏和强色区域偏移", "粗晶群体规则性仍可见"],
    discoveries: ["感知到的蓝偏主要是非线性对比/色度比例，而不一定是白平衡", "相机噪声不能被误当成胶片颗粒保留"],
    refs: ["R7", "R8"],
  },
  {
    version: "V19",
    year: "有机颗粒",
    title: "多分散染料云与逐帧沸腾",
    status: "calibration",
    projection: { src: "/versions/v19-projection.jpg", label: "有机颗粒放映" },
    bluray: { src: "/versions/v19-bluray.jpg", label: "有机颗粒蓝光" },
    summary: "每个速度群体拆为三种尺寸类别，加入亚像素相位和稀疏大云，使颗粒运动减少数字彩噪感。",
    changes: ["多分散尺寸", "亚像素相位", "小颗粒占主导、稀疏大云提供生命力"],
    errors: ["亚层的颜色贡献仍静态", "DIR仍在亚层合并之后", "所有颜色记录仍共享代表性ECD"],
    discoveries: ["有机感来自统计形态的不规则与连续尺寸，而不是增大噪点", "逐帧新采样必须保持密度均值不漂移"],
    refs: ["R1", "R2", "R7"],
  },
  {
    version: "V20",
    year: "当前版本",
    title: "曝光相关的亚层染料贡献",
    status: "current",
    projection: { src: "/versions/v20-projection.jpg", label: "V20 · 2383放映" },
    bluray: { src: "/versions/v20-bluray.jpg", label: "V20 · 2K DI / 蓝光" },
    summary: "快、中、慢层根据边际激活量改变色记录贡献；薄负片的颜色分离更宽，高曝光慢层更接近纯记录。",
    changes: ["边际激活混色", "颗粒与色彩形成首次耦合", "扫描肩部校正更自然地释放"],
    errors: ["DIR仍是总密度后的二维近似", "扫描器和Status-M仍被混为同一个观察器", "亚层尺寸没有按颜色记录独立"],
    discoveries: ["柯达同期专利显示胶片设计会预补偿Telecine红通道", "彩色负片最终承载影像的是染料云，显影银影会被移除", "V21必须重排算法顺序，而不是继续调矩阵"],
    refs: ["R2", "R3", "R6", "R11", "R12"],
  },
];

export const references = [
  { id: "R1", title: "KODAK VISION 500T 5279 / 7279 Technical Data, H-1-5279t", type: "Kodak片种数据", url: "https://125px.com/docs/motionpicture/kodak/5279.pdf" },
  { id: "R2", title: "Exploring the Color Image", type: "Kodak技术读物", url: "https://www.kodak.com/content/products-brochures/Film/Exploring-the-Color-Image.pdf" },
  { id: "R3", title: "Processing KODAK Motion Picture Films, Module 7: ECN-2", type: "Kodak处理规范", url: "https://www.kodak.com/content/products-brochures/Film/Processing-KODAK-Motion-Picture-Films-Module-7.pdf" },
  { id: "R4", title: "KODAK VISION Color Print Film 2383 / 3383 Technical Data", type: "Kodak正片数据", url: "https://www.kodak.com/content/products-brochures/Film/VISION-Color-Print-Film-2383-3383-TECHNICAL-DATA.pdf" },
  { id: "R5", title: "LAD — Laboratory Aim Density, KODAK H-61", type: "Kodak实验室控制", url: "https://www.kodak.com/content/products-brochures/Film/LAD-Laboratory-Aim-Density.pdf" },
  { id: "R6", title: "US 5,298,376 — DIR inhibitor transport and colour saturation", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5298376A/en" },
  { id: "R7", title: "US 5,314,793 — multilayer speed and granularity architecture", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5314793A/en" },
  { id: "R8", title: "Spirit DataCine / Spirit HD technical data", type: "DFT扫描器资料", url: "https://www.dft-film.com/downloads/datasheets/DFT-Spirit-HD-datasheet-11-09.pdf" },
  { id: "R9", title: "Digital Intermediates, August 2003", type: "同期后期制作报道", url: "https://www.postmagazine.com/Publications/Post-Magazine/2003/August-1-2003/DIGITAL-INTERMEDIATES.aspx" },
  { id: "R10", title: "Charlie’s Angels: Full Throttle — technical specifications", type: "完成态参考", url: "https://www.imdb.com/title/tt0305357/technical/" },
  { id: "R11", title: "US 5,500,316 — colour negative contrast adjusted for electronic scanning", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5500316A/en" },
  { id: "R12", title: "US 5,705,327 — nonlinear curve shape for telecine transfer", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5705327A/en" },
  { id: "R13", title: "The Chemistry of Kodak Film — Smarter Every Day 275-C", type: "柯达工厂访谈", url: "https://www.youtube.com/watch?v=zJ8aNPStQ8M" },
  { id: "R14", title: "Kodak’s Film Quality Control Process — 275-B", type: "柯达工厂质控", url: "https://www.youtube.com/watch?v=VIH0dEMyv9w" },
  { id: "R15", title: "Advanced Emulsion: crystals, couplers, masks and processing", type: "Kodak资料支持的讲解", url: "https://www.youtube.com/watch?v=I4_7tW-cx1I" },
];

export const refMap = Object.fromEntries(references.map((ref) => [ref.id, ref]));
