export type BranchImage = {
  src: string;
  label: string;
  inherited?: boolean;
  videoSrc?: string;
};

export type ParameterGroup = {
  title: string;
  titleEn?: string;
  items: { label: string; labelEn?: string; value: string; valueEn?: string; note?: string; noteEn?: string }[];
};

export type VersionEntry = {
  version: string;
  year: string;
  title: string;
  status: "prototype" | "calibration" | "current";
  projection: BranchImage;
  bluray: BranchImage;
  summary: string;
  changes: string[];
  errors: string[];
  discoveries: string[];
  refs: string[];
  parameters?: ParameterGroup[];
  additionalTrials?: {
    name: string;
    note: string;
    projection: BranchImage;
    bluray: BranchImage;
  }[];
};

const common = (version: string): BranchImage => ({
  src: `/versions/${version}-main.jpg`,
  label: "当时尚未拆分两条观看链；这里保留同一实验主图",
  inherited: true,
});

export const versions: VersionEntry[] = [
  {
    version: "V4",
    year: "结构原型",
    title: "让清晰度与颗粒属于同一种介质",
    status: "prototype",
    projection: common("v4"),
    bluray: common("v4"),
    summary: "第一次停止在成片上覆盖噪点，改为从虚拟乳剂密度场形成图像，并让MTF和颗粒共同决定细节。",
    changes: ["建立曝光域乳剂原型", "加入通道相关的MTF", "保留逐帧随机结构"],
    errors: ["颗粒半径和观察模糊过大", "更接近8mm/16mm，而不是35mm 5279", "颜色仍主要来自经验矩阵"],
    discoveries: ["粗颗粒必须伴随较低的高频清晰度", "颗粒不是独立贴图，而是画面形成机制的一部分"],
    refs: ["R1", "R2"],
  },
  {
    version: "V5",
    year: "5279定标",
    title: "从“胶片感”转向指定片种",
    status: "prototype",
    projection: common("v5"),
    bluray: common("v5"),
    summary: "开始以Kodak VISION 500T 5279的数据表为约束，不再把所有高速彩色负片视为同一种风格。",
    changes: ["引入5279感色与曲线目标", "建立35mm画幅尺度", "开始区分R/G/B记录"],
    errors: ["高光仍受RAW解码和显示端裁切影响", "暗部颗粒偏彩色电子噪声", "三层乳剂尚未显式建模"],
    discoveries: ["5279的蓝记录颗粒测量显著高于绿、红记录", "片种性格必须由曲线、染料和颗粒共同决定"],
    refs: ["R1"],
  },
  {
    version: "V6",
    year: "RAW高光",
    title: "先救回传感器信息，再谈胶片肩部",
    status: "prototype",
    projection: common("v6"),
    bluray: common("v6"),
    summary: "修正GH7 ProRes RAW的线性解释与高光路径，把摄像机裁切和负片肩部压缩分离。",
    changes: ["保持RAW在线性域", "加入分记录高光肩部", "限制极高曝光的长程红层散射"],
    errors: ["颗粒依旧过猛", "高光光学效应曾被做成通用红光晕", "Panasonic色彩变换还不够严格"],
    discoveries: ["负片高光不是简单soft clip", "rem-jet会显著抑制背面散射，5279不应出现夸张光晕"],
    refs: ["R1", "R2", "R3"],
  },
  {
    version: "V7",
    year: "胶片光学",
    title: "把卤化银、散射与防光晕放进同一条链",
    status: "prototype",
    projection: common("v7"),
    bluray: common("v7"),
    summary: "补入乳剂层散射、防光晕层和局部边缘响应，画面开始从均匀噪声变成密度相关的结构。",
    changes: ["曝光相关颗粒", "受控halation", "颗粒与边缘响应耦合"],
    errors: ["形态仍像被推冲的16mm", "三种速度层只是宏观分段", "黑位和观看条件尚未分离"],
    discoveries: ["暗部、亮部的颗粒差异来自不同速度群体进入显影区间", "清晰度匹配比单纯降低噪点更重要"],
    refs: ["R2", "R3"],
  },
  {
    version: "V8",
    year: "35mm细化",
    title: "从生猛16mm收回到细腻35mm",
    status: "calibration",
    projection: common("v8"),
    bluray: common("v8"),
    summary: "缩小染料云、提高有效位点数量、减弱暗部密度摆幅，让颗粒频率和5279的35mm观感接近。",
    changes: ["颗粒半径降至约0.5–1.3原生像素", "增加有效染料云数量", "减弱暗部彩色分离"],
    errors: ["平均响应仍依赖共享曲线", "扫描和放映还没有各自的物理观察器", "染料遮罩没有光谱化"],
    discoveries: ["细腻并不等于静止：更小、更密的位点仍可产生有机逐帧变化"],
    refs: ["R1", "R2"],
  },
  {
    version: "V9",
    year: "双分支起点",
    title: "5279负片曲线、光谱染料与两种观看结果",
    status: "calibration",
    projection: { src: "/versions/v9-projection.jpg", label: "早期正片解释" },
    bluray: { src: "/versions/v9-bluray.jpg", label: "5279负片扫描解释" },
    summary: "首次分别采样5279红、绿、蓝Status-M曲线，并建立扫描与印片两条观看分支。",
    changes: ["三条独立H-D曲线", "净染料密度的初步光谱模型", "扫描与正片分离"],
    errors: ["正片仍是经验性正值染料矩阵", "未完整保留橙色底和有色耦合剂的负密度瓣", "两条分支的色彩基准不统一"],
    discoveries: ["5279数据表的染料曲线是D-min已扣除的净变化，并非纯染料吸收", "遮罩耦合剂必须只计算一次"],
    refs: ["R1", "R2", "R4"],
  },
  {
    version: "V10",
    year: "2383初版",
    title: "把Kodak 2383作为第二种真实材料",
    status: "calibration",
    projection: { src: "/versions/v10-projection.jpg", label: "5279 → 2383 初版" },
    bluray: { src: "/versions/v9-bluray.jpg", label: "扫描分支沿用V9", inherited: true },
    summary: "加入2383的感光曲线、染料和印片灯，使放映不再是对负片做一条显示LUT。",
    changes: ["第二套H-D曲线", "LAD目标密度", "2383染料与正片颗粒"],
    errors: ["曾把净负密度曲线当成纯正值染料，造成严重紫红偏色", "橙色底被错误去除或重复补偿", "正片陡峭曲线放大了小型光谱误差"],
    discoveries: ["光学印片必须保留5279 D-min/橙色底在光路中", "扫描去底与印片补偿不是同一操作"],
    refs: ["R1", "R3", "R4"],
  },
  {
    version: "V11",
    year: "灰阶校准",
    title: "不只校准18%灰，而是校准整条灰阶",
    status: "calibration",
    projection: { src: "/versions/v11-projection.jpg", label: "2383氙灯放映" },
    bluray: { src: "/versions/v11-bluray.jpg", label: "Cineon / Spirit 2K扫描" },
    summary: "用LAD与多级灰阶约束中性，建立Cineon编码和Spirit式扫描基础。",
    changes: ["多点中性灰校准", "Cineon代码值95/445锚点", "两条分支统一Rec.709输出"],
    errors: ["局部颜色仍由粗糙矩阵修正", "扫描器光谱被近似为Status-M", "蓝光完成阶段黑位尚未单独设计"],
    discoveries: ["中灰中性并不能保证高光和暗部中性", "黑位是观看链决策，不应倒推修改负片D-min"],
    refs: ["R5", "R8"],
  },
  {
    version: "V12",
    year: "有色遮罩",
    title: "保留有色耦合剂的净负密度",
    status: "calibration",
    projection: { src: "/versions/v12-projection.jpg", label: "修正遮罩后的放映" },
    bluray: { src: "/versions/v12-bluray.jpg", label: "修正遮罩后的扫描" },
    summary: "将5279数据表的21点光谱曲线作为带符号的净密度变化，正确解释有色遮罩。",
    changes: ["21波长光谱LUT", "保留小型负密度瓣", "DIR局部邻接初版"],
    errors: ["扫描端仍使用窄带观察器", "DIR在总密度形成后才计算", "色彩分离缺少亚层依赖"],
    discoveries: ["负值不是数据错误，而是遮罩耦合剂被消耗的方向", "平均校正平坦仍会留下片种特有的光谱残差"],
    refs: ["R1", "R2", "R3", "R6"],
  },
  {
    version: "V13",
    year: "投影光源",
    title: "从黑体白光改为电影氙灯光谱",
    status: "calibration",
    projection: { src: "/versions/v13-projection.jpg", label: "修正后的2383氙灯放映" },
    bluray: { src: "/versions/v13-bluray.jpg", label: "Spirit 2K扫描" },
    summary: "加入氙灯的非平滑光谱结构、CIE观察器和投影散射。早期放映版的紫红错误也被明确记录并修正。",
    changes: ["氙灯SPD", "CIE XYZ观察", "Callier/投影散射的保守近似"],
    errors: ["第一版放映严重紫红，根因是打印光谱与染料解释叠加错误", "显示器上观看物理放映结果时，对比和色浓度过强"],
    discoveries: ["“物理投影”与“在显示器上呈现投影质感”需要两个不同目标", "小色相误差会被2383陡峭曲线放大"],
    refs: ["R2", "R4", "R7"],
  },
  {
    version: "V14",
    year: "三速度层",
    title: "有限快／中／慢感光位点",
    status: "calibration",
    projection: { src: "/versions/v14-projection.jpg", label: "多层颗粒放映" },
    bluray: { src: "/versions/v14-bluray.jpg", label: "多层颗粒扫描" },
    summary: "每个颜色记录拥有快、中、慢三组有限位点，以二项统计形成曝光相关颗粒，并严格回标5279的48µm RMS曲线。",
    changes: ["9组有限位点", "p(1−p)方差", "48µm测量孔径校准"],
    errors: ["R/G/B共用一套代表性颗粒尺寸", "每组内部仍是单一圆形尺寸", "颗粒颜色相关性不够有机"],
    discoveries: ["位点接近全显影时方差会再次下降", "‘阴影粗、亮部细’是群体转换，不是简单亮度遮罩"],
    refs: ["R1", "R2", "R7"],
  },
  {
    version: "V15",
    year: "完整印片光路",
    title: "橙色底、印片灯、2383与色域映射",
    status: "calibration",
    projection: { src: "/versions/v15-projection.jpg", label: "完整光谱印片链" },
    bluray: { src: "/versions/v15-bluray.jpg", label: "扫描链校准" },
    summary: "在全波长光路中保留橙色底，用印片灯补偿并通过2383形成正片；加入RGB分离补偿。",
    changes: ["D-min全光谱传输", "印片灯中性补偿", "H-61/TAF式颜色分离校准"],
    errors: ["投影颜色仍偏深、偏蓝", "暗红和绿色曾发生大角度色相旋转", "扫描黑位与颗粒积分顺序仍有问题"],
    discoveries: ["投影浓郁感一部分是2383斜率，另一部分可能是错误观看适配", "色域压缩必须尽量保持恒定色相"],
    refs: ["R3", "R4", "R5"],
  },
  {
    version: "V16",
    year: "观看链校准",
    title: "放映黑、扫描黑与色相稳定",
    status: "calibration",
    projection: { src: "/versions/v16-projection.jpg", label: "典型16 ft-L放映" },
    bluray: { src: "/versions/v16-bluray.jpg", label: "2K DI / 蓝光完成" },
    summary: "分离无杂散光投影、典型影院投影和蓝光完成；用OKLab恒色相压缩修正暗部色偏。",
    changes: ["典型1%投影flare", "OKLab恒色相压缩", "蓝光下段gamma与真实黑锚点"],
    errors: ["蓝光颗粒会在显示黑边界形成单边偏置", "投影在显示器上仍显得过重", "扫描高频彩色颗粒多于参考影片"],
    discoveries: ["投影黑位和蓝光黑位来自不同物理/显示链", "《霹雳娇娃2》只能约束完成态，不能当作未调色5279测量"],
    refs: ["R8", "R9", "R10"],
  },
  {
    version: "V17",
    year: "扫描修正",
    title: "在透射光域完成Spirit 2K积分",
    status: "calibration",
    projection: { src: "/versions/v16-projection.jpg", label: "放映分支沿用V16", inherited: true },
    bluray: { src: "/versions/v17-bluray.jpg", label: "V17透射域扫描" },
    summary: "扫描器先对穿过负片的光做2K面积积分，再转回密度和Cineon，解决黑场被颗粒抬起的问题。",
    changes: ["透射域2K孔径", "显示边界之后才形成", "蓝光高频色度颗粒受控积分"],
    errors: ["物理放映与显示器观看仍未适配", "扫描观察器仍近似Status-M", "颗粒形态还太规则"],
    discoveries: ["扫描器看到的是透射光，不是已经裁到黑的正片RGB", "正确的运算顺序本身就能修复浮黑"],
    refs: ["R8", "R10"],
  },
  {
    version: "V18",
    year: "显示适配",
    title: "区分物理2383投影与显示器上的放映质感",
    status: "calibration",
    projection: { src: "/versions/v18-projection.jpg", label: "2383显示器观看适配" },
    bluray: { src: "/versions/v17-bluray.jpg", label: "蓝光分支沿用V17", inherited: true },
    summary: "保留物理投影分支，同时建立适合Rec.709显示器判断的投影外观；分离GH7传感器噪声和虚拟乳剂颗粒。",
    changes: ["投影monitor分支", "中性灰多锚点适配", "场景线性传感器噪声分离"],
    errors: ["早期适配仍有轻微蓝偏和强色区域偏移", "粗晶群体规则性仍可见"],
    discoveries: ["感知到的蓝偏主要是非线性对比/色度比例，而不一定是白平衡", "相机噪声不能被误当成胶片颗粒保留"],
    refs: ["R7", "R8"],
  },
  {
    version: "V19",
    year: "有机颗粒",
    title: "多分散染料云与逐帧沸腾",
    status: "calibration",
    projection: { src: "/versions/v19-projection.jpg", label: "有机颗粒放映" },
    bluray: { src: "/versions/v19-bluray.jpg", label: "有机颗粒蓝光" },
    summary: "每个速度群体拆为三种尺寸类别，加入亚像素相位和稀疏大云，使颗粒运动减少数字彩噪感。",
    changes: ["多分散尺寸", "亚像素相位", "小颗粒占主导、稀疏大云提供生命力"],
    errors: ["亚层的颜色贡献仍静态", "DIR仍在亚层合并之后", "所有颜色记录仍共享代表性ECD"],
    discoveries: ["有机感来自统计形态的不规则与连续尺寸，而不是增大噪点", "逐帧新采样必须保持密度均值不漂移"],
    refs: ["R1", "R2", "R7"],
  },
  {
    version: "V20",
    year: "上一版",
    title: "曝光相关的亚层染料贡献",
    status: "calibration",
    projection: { src: "/versions/v20-projection.jpg", label: "V20 · 2383放映" },
    bluray: { src: "/versions/v20-bluray.jpg", label: "V20 · 2K DI / 蓝光" },
    summary: "快、中、慢层根据边际激活量改变色记录贡献；薄负片的颜色分离更宽，高曝光慢层更接近纯记录。",
    changes: ["边际激活混色", "颗粒与色彩形成首次耦合", "扫描肩部校正更自然地释放"],
    errors: ["DIR仍是总密度后的二维近似", "扫描器和Status-M仍被混为同一个观察器", "亚层尺寸没有按颜色记录独立"],
    discoveries: ["柯达同期专利显示胶片设计会预补偿Telecine红通道", "彩色负片最终承载影像的是染料云，显影银影会被移除", "V21必须重排算法顺序，而不是继续调矩阵"],
    refs: ["R2", "R3", "R6", "R11", "R12"],
  },
  {
    version: "V21",
    year: "上一版",
    title: "让显影、颗粒与观察器真正分开工作",
    status: "calibration",
    projection: { src: "/versions/v21-projection.jpg", label: "V21 · 2383氙灯放映显示适配" },
    bluray: { src: "/versions/v21-bluray.jpg", label: "V21 · Period 2K / Cineon蓝光" },
    summary: "DIR改在九个快／中／慢群体显影时发生；三条颜色记录拥有独立颗粒形态；Status-M、时期Telecine和2383印片成为三个不同的光谱观察器。与此同时修正了V20放映版几乎继承扫描版色度、只留下更深黑位的错误。",
    changes: ["九群体显影域DIR反应—扩散", "青／品红／黄记录独立快中慢形态", "Status-M、Period 2K、2383三观察器分离", "重建2383显示器观看适配，不再复制扫描色相与饱和度"],
    errors: ["V20的投影显示适配从扫描分支继承约92%色相和94%饱和度，使两张截图除了黑位外过度接近", "5279真实亚层配方与时期Telecine精确光谱仍未公开，当前参数是受数据表和同期专利约束的模型", "显示器上的放映版仍是对16 ft-L影院观看的适配，不等同于银幕实测光谱"],
    discoveries: ["中性H-D可以在DIR重排后保持到约2.4×10⁻⁷ D，同时让局部与层间反应发生", "48µm孔径下三记录RMS误差保持在约0–1.5%", "放映与扫描应共享中性明度目标，却不能共享色度；V21代表帧的中位色相差约4.8°"],
    refs: ["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R11", "R12"],
  },
  {
    version: "V22",
    year: "上一版",
    title: "分析染料、层间耦合与相对白点放映预览",
    status: "calibration",
    projection: { src: "/versions/v22-projection.jpg", label: "V22 · 5279 → 2383氙灯放映" },
    bluray: { src: "/versions/v22-bluray.jpg", label: "V22 · Period 2K / Cineon蓝光" },
    summary: "修正V21把2383 Status-A积分密度再次当作独立CMY染料量的结构错误：先非线性反解分析染料量，再经LAD锚定的层间曝光耦合进入正片曲线。物理胶片与显示器预览被明确拆分，D60目标只提供去除自身中性白点后的相对色度校准。",
    changes: ["非线性Status-A积分密度→分析染料量反演", "LAD锚定的印片层间曝光矩阵", "去除D60中性响应的显示器相对色度校准", "放映与扫描共享同一帧5279乳剂随机实现"],
    errors: ["V21把积分测量值再次乘以染料光谱，重复计算了不希望吸收", "D60是公开厂商的显示目标，不是Kodak工厂化学参数", "5279实拍色卡、肤色靶和影院分光测量仍未获得；当前母版只有6帧"],
    discoveries: ["公开胶片化学只约束胶片与氙灯，影院外观转到Rec.709还需要独立观看适配", "厂商D60变换的绝对白点必须先减去，否则会把整张画面染紫红", "13项三次多项式无法压缩该非线性修正，25³相对色度格点才通过保持测试", "六色中位色相误差从V21的7.94°降至1.46°；实拍帧进入D55–D65色相包络的像素从20.2%升至45.9%"],
    refs: ["R1", "R4", "R5", "R16", "R17", "R18", "R19", "R20"],
    parameters: [
      { title: "输入与母版", items: [
        { label: "源素材", value: "GH7 Open Gate ProRes RAW HQ" },
        { label: "RAW解码", value: "Apple extended-linear BT.2020 · float32" },
        { label: "相机色彩", value: "Panasonic官方RAW → V-Gamut" },
        { label: "虚拟曝光", value: "+0.45 stop" },
        { label: "画幅", value: "5760 × 4320 · 4:3" },
        { label: "帧率", value: "24000/1001 · 23.976 fps" },
        { label: "测试段", value: "Frame 9–14 · 6帧" },
        { label: "母版", value: "ProRes 4444 · yuv444p12le" },
        { label: "显示编码", value: "Rec.709 · 1-1-1" },
      ] },
      { title: "5279乳剂", items: [
        { label: "片种", value: "KODAK VISION 500T 5279" },
        { label: "假定成像宽", value: "24.9 mm" },
        { label: "亚层结构", value: "R/G/B × 快/中/慢 × 3粒径" },
        { label: "速度偏移", value: "0.00 / 0.50 / 1.30 logE" },
        { label: "容量比例 快/中/慢", value: "126 / 149 / 161" },
        { label: "快层中心 R/G/B", value: "−2.034 / −2.018 / −2.112 logE" },
        { label: "转折宽度 R/G/B", value: "0.550 / 0.572 / 0.525" },
        { label: "ECD 青记录", value: "1.28 / 0.83 / 0.58 µm" },
        { label: "ECD 品红记录", value: "1.36 / 0.79 / 0.52 µm" },
        { label: "ECD 黄记录", value: "1.14 / 0.88 / 0.68 µm" },
        { label: "颗粒校准孔径", value: "48 µm diffuse RMS" },
        { label: "颗粒相关尺度", value: "0.88" },
        { label: "粒径占比", value: "0.30 / 0.53 / 0.17" },
        { label: "粒径半径倍率", value: "0.70 / 1.00 / 1.42" },
        { label: "光学倍率", value: "0.82 / 1.00 / 1.20" },
        { label: "亚像素相位半径", value: "0.38 px @ 5760" },
        { label: "光学σ 青记录", value: "0.59 / 0.43 / 0.34 px" },
        { label: "光学σ 品红记录", value: "0.63 / 0.41 / 0.31 px" },
        { label: "光学σ 黄记录", value: "0.54 / 0.45 / 0.37 px" },
        { label: "有效位点 青记录", value: "17 / 60 / 79 px⁻¹" },
        { label: "有效位点 品红记录", value: "16 / 64 / 88 px⁻¹" },
        { label: "有效位点 黄记录", value: "22 / 55 / 70 px⁻¹" },
        { label: "负片MTF σ R/G/B", value: "0.85 / 0.67 / 0.60 px" },
        { label: "感色重叠 Row R", value: "0.94 / 0.05 / 0.01" },
        { label: "感色重叠 Row G", value: "0.04 / 0.92 / 0.04" },
        { label: "感色重叠 Row B", value: "0.01 / 0.08 / 0.91" },
      ] },
      { title: "DIR显影耦合", items: [
        { label: "发生阶段", value: "九亚层合并前的显影域" },
        { label: "扩散σ 快/中/慢", value: "4.8 / 3.1 / 1.9 px @ 5760" },
        { label: "层间强度", value: "0.085" },
        { label: "层内强度 R/G/B", value: "0.028 / 0.042 / 0.058" },
        { label: "随机耦合", value: "0.42" },
        { label: "释放增益 快/中/慢", value: "0.90 / 1.00 / 0.82" },
        { label: "接收增益 快/中/慢", value: "0.72 / 1.00 / 0.84" },
        { label: "传输矩阵 Row 1", value: "0.34 / 0.22 / 0.10" },
        { label: "传输矩阵 Row 2", value: "0.22 / 0.30 / 0.18" },
        { label: "传输矩阵 Row 3", value: "0.10 / 0.18 / 0.24" },
        { label: "中性约束", value: "均匀H-D严格不漂移" },
      ] },
      { title: "2383放映链", items: [
        { label: "正片", value: "KODAK VISION 2383" },
        { label: "Status-A D-min R/G/B", value: "0.04356 / 0.04749 / 0.10272 D" },
        { label: "LAD目标", value: "1.00 D" },
        { label: "D-max", value: "4.10 D" },
        { label: "印片光", value: "3200 K" },
        { label: "放映光", value: "Kodak参考氙灯SPD" },
        { label: "Callier修正", value: "1.0–1.4% density" },
        { label: "典型影院flare", value: "1.0%" },
        { label: "正片MTF σ R/G/B", value: "0.34 / 0.27 / 0.52 px" },
        { label: "层间矩阵 Row 1", value: "1.4105 / −0.9566 / 0.9152" },
        { label: "层间矩阵 Row 2", value: "0.4127 / 0.6943 / −0.2324" },
        { label: "层间矩阵 Row 3", value: "−0.5640 / 0.6093 / 0.8425", note: "识别值，不宣称是Kodak工厂矩阵" },
      ] },
      { title: "显示器放映预览", items: [
        { label: "物理亮度权重", value: "0.50" },
        { label: "最大物理色相权重", value: "1.00" },
        { label: "最大物理饱和权重", value: "0.60" },
        { label: "色度校准", value: "D60相对Oklab a/b · L不变" },
        { label: "校准格点", value: "25³ × 3" },
        { label: "中性保护", value: "Cineon chroma 0.008 → 0.040" },
        { label: "插值余量", value: "0.99" },
        { label: "扫描亮度锚点", value: "0 / .00087 / .00863 / .03523 / .09330 / .18 / .27646 / .38707 / .51532 / .66216 / 1" },
        { label: "目标亮度锚点", value: "0 / .00320 / .01010 / .02374 / .06445 / .17997 / .36756 / .54039 / .67413 / .78203 / .97460" },
        { label: "色域映射", value: "Oklab恒色相压缩" },
      ] },
      { title: "Period 2K / 蓝光", items: [
        { label: "扫描观察器", value: "Spirit式宽带RGB · 620/540/470 nm" },
        { label: "扫描孔径", value: "2048 RGB line-array" },
        { label: "Cineon", value: "10-bit · black 95 · 0.002 D/CV" },
        { label: "中性灰码值", value: "445" },
        { label: "主色校正强度", value: "0.82" },
        { label: "肩部释放", value: "0.04" },
        { label: "蓝光下段gamma", value: "1.20" },
        { label: "色度颗粒σ", value: "0.55 @ 2K" },
        { label: "高频色度保留", value: "0.55" },
        { label: "硬件Grain Manager", value: "Off" },
      ] },
    ],
  },
  {
    version: "V23",
    year: "当前版本",
    title: "连续染料云群体与跨场景颜色保持",
    status: "current",
    projection: { src: "/versions/v23-t020-projection.jpg", label: "T020 · 5279 → 2383氙灯放映" },
    bluray: { src: "/versions/v23-t020-bluray.jpg", label: "T020 · Period 2K / Cineon蓝光" },
    summary: "在树皮、蘑菇、亮叶与天空，以及雨天青绿场景上复测V22颜色；拒绝了没有实际收益的D55/D60/D65三白点候选。颗粒由三种离散尺寸改成五点连续分布近似，并以黄金角改变亚像素相位，使沸腾更细、更不规则，同时继续回标5279公开的48µm RMS。",
    changes: ["两段新GH7 ProRes RAW各制作1秒双母版，用短片先验证方向", "三尺寸染料云改为五点连续分布近似", "黄金角亚像素相位减少规则重复", "颗粒相关尺度0.88降至0.86", "193³完整放映映射加速并逐像素验证", "记录真实并行制作时间"],
    errors: ["D55/D60/D65三白点相对色度候选与V22 D60结果数值上几乎相同，因此被拒绝", "公开数据仍未给出5279真实染料云尺寸分布；五点分布是受颗粒、MTF与同期结构约束的数值近似", "5279快/中/慢层的真实成色剂量和分层染料光谱未公开；当前曝光相关染料贡献仍是受限模型", "193³加速格点在极少数非线性边界点仍有局部误差；真实帧99%像素Oklab ΔE小于约0.36"],
    discoveries: ["颜色候选必须在新场景上产生可测收益，否则保持已验证模型比继续调色更准确", "颗粒的有机性可由尺寸连续性和相位非周期性提高，不需要增加RMS幅度", "同期Kodak结构会限制最高速层的成色剂量；暗部色噪与分层染料形成相互耦合", "完整物理颜色链可被高密度格点安全缓存；真实帧逐像素放映变换约加速14倍", "T020和T032分别考验高光/暗树皮与青绿/低对比场景，适合作为以后版本的固定泛化测试"],
    refs: ["R1", "R2", "R4", "R7", "R21", "R22", "R23", "R24"],
    additionalTrials: [{
      name: "NJARAW_S001_S001_T032",
      note: "雨天青绿、暗柱与湿地低对比场景；用于检查绿色色相、阴影颗粒和扫描黑位。",
      projection: { src: "/versions/v23-t032-projection.jpg", label: "T032 · 5279 → 2383氙灯放映" },
      bluray: { src: "/versions/v23-t032-bluray.jpg", label: "T032 · Period 2K / Cineon蓝光" },
    }],
    parameters: [
      { title: "输入与母版", items: [
        { label: "源素材 A", value: "NJARAW_S001_S001_T020" },
        { label: "源素材 B", value: "NJARAW_S001_S001_T032" },
        { label: "相机 / 记录", value: "Panasonic GH7 · Atomos Ninja · ProRes RAW HQ" },
        { label: "拍摄参数", value: "ISO 500 · 5500 K · 180°" },
        { label: "RAW解码", value: "Apple extended-linear BT.2020 · float32" },
        { label: "相机色彩", value: "Panasonic官方RAW → V-Gamut" },
        { label: "虚拟曝光", value: "+0.45 stop" },
        { label: "画幅 / 帧率", value: "5760 × 4320 · 24000/1001" },
        { label: "每段长度", value: "24帧 · 1.001秒" },
        { label: "母版", value: "ProRes 4444 · yuv444p12le" },
        { label: "显示编码", value: "Rec.709 · 1-1-1" },
      ] },
      { title: "5279乳剂与颗粒", items: [
        { label: "片种 / 成像宽", value: "VISION 500T 5279 · 24.9 mm" },
        { label: "亚层结构", value: "R/G/B × 快/中/慢 × 5粒径" },
        { label: "速度偏移", value: "0.00 / 0.50 / 1.30 logE" },
        { label: "容量比例 快/中/慢", value: "126 / 149 / 161" },
        { label: "快层中心 R/G/B", value: "−2.034 / −2.018 / −2.112 logE" },
        { label: "转折宽度 R/G/B", value: "0.550 / 0.572 / 0.525" },
        { label: "ECD 青记录", value: "1.28 / 0.83 / 0.58 µm" },
        { label: "ECD 品红记录", value: "1.36 / 0.79 / 0.52 µm" },
        { label: "ECD 黄记录", value: "1.14 / 0.88 / 0.68 µm" },
        { label: "颗粒校准", value: "Kodak 48 µm diffuse RMS" },
        { label: "颗粒相关尺度", value: "0.86" },
        { label: "五级占比", value: "0.10 / 0.24 / 0.34 / 0.22 / 0.10" },
        { label: "半径倍率", value: "0.62 / 0.78 / 0.98 / 1.22 / 1.55" },
        { label: "光学倍率", value: "0.78 / 0.88 / 1.00 / 1.12 / 1.25" },
        { label: "相位步进", value: "2.399963 rad · 黄金角" },
        { label: "亚像素相位半径", value: "0.38 px @ 5760" },
        { label: "光学σ 青记录", value: "0.59 / 0.43 / 0.34 px" },
        { label: "光学σ 品红记录", value: "0.63 / 0.41 / 0.31 px" },
        { label: "光学σ 黄记录", value: "0.54 / 0.45 / 0.37 px" },
        { label: "有效位点 青记录", value: "17 / 60 / 79 px⁻¹" },
        { label: "有效位点 品红记录", value: "16 / 64 / 88 px⁻¹" },
        { label: "有效位点 黄记录", value: "22 / 55 / 70 px⁻¹" },
        { label: "随机种子", value: "逐帧、逐记录、逐速度群独立" },
        { label: "负片MTF σ R/G/B", value: "0.85 / 0.67 / 0.60 px" },
        { label: "感色重叠 Row R", value: "0.94 / 0.05 / 0.01" },
        { label: "感色重叠 Row G", value: "0.04 / 0.92 / 0.04" },
        { label: "感色重叠 Row B", value: "0.01 / 0.08 / 0.91" },
        { label: "传感器噪声", value: "photochemical separation" },
      ] },
      { title: "DIR显影耦合", items: [
        { label: "DIR阶段", value: "九亚层合并前的显影域" },
        { label: "DIR扩散σ", value: "4.8 / 3.1 / 1.9 px" },
        { label: "层间强度", value: "0.085" },
        { label: "层内强度 R/G/B", value: "0.028 / 0.042 / 0.058" },
        { label: "随机耦合", value: "0.42" },
        { label: "释放增益 快/中/慢", value: "0.90 / 1.00 / 0.82" },
        { label: "接收增益 快/中/慢", value: "0.72 / 1.00 / 0.84" },
        { label: "传输矩阵 Row 1", value: "0.34 / 0.22 / 0.10" },
        { label: "传输矩阵 Row 2", value: "0.22 / 0.30 / 0.18" },
        { label: "传输矩阵 Row 3", value: "0.10 / 0.18 / 0.24" },
        { label: "中性约束", value: "均匀H-D严格不漂移" },
      ] },
      { title: "染料与2383放映", items: [
        { label: "5279染料", value: "D-min已扣除的带符号净光谱密度" },
        { label: "2383分析染料", value: "非线性Status-A积分反演" },
        { label: "Status-A D-min R/G/B", value: "0.04356 / 0.04749 / 0.10272 D" },
        { label: "LAD目标 / D-max", value: "1.00 D / 4.10 D" },
        { label: "印片 / 放映光", value: "3200 K / Kodak氙灯SPD" },
        { label: "层间矩阵 Row 1", value: "1.4105 / −0.9566 / 0.9152" },
        { label: "层间矩阵 Row 2", value: "0.4127 / 0.6943 / −0.2324" },
        { label: "层间矩阵 Row 3", value: "−0.5640 / 0.6093 / 0.8425", note: "识别值，不宣称是Kodak工厂矩阵" },
        { label: "物理亮度权重", value: "0.50" },
        { label: "最大物理色相权重", value: "1.00" },
        { label: "最大物理饱和权重", value: "0.60" },
        { label: "显示色度校准", value: "D60相对Oklab a/b · L不变" },
        { label: "相对色度格点", value: "25³ × 3" },
        { label: "中性保护", value: "Cineon chroma 0.008 → 0.040" },
        { label: "颜色决定", value: "沿用V22", note: "三白点候选没有产生可测泛化收益" },
        { label: "扫描亮度锚点", value: "0 / .00087 / .00863 / .03523 / .09330 / .18 / .27646 / .38707 / .51532 / .66216 / 1" },
        { label: "目标亮度锚点", value: "0 / .00320 / .01010 / .02374 / .06445 / .17997 / .36756 / .54039 / .67413 / .78203 / .97460" },
        { label: "色域映射", value: "Oklab恒色相压缩" },
      ] },
      { title: "扫描与放映输出", items: [
        { label: "扫描观察器", value: "Spirit式宽带RGB · 620/540/470 nm" },
        { label: "扫描孔径", value: "2048 RGB line-array" },
        { label: "Cineon", value: "10-bit · black 95 · 0.002 D/CV · gray 445" },
        { label: "主色校正强度", value: "0.82" },
        { label: "肩部释放", value: "0.04" },
        { label: "蓝光下段gamma", value: "1.20" },
        { label: "色度颗粒σ / 高频", value: "0.55 @ 2K / 0.55" },
        { label: "正片MTF σ R/G/B", value: "0.34 / 0.27 / 0.52 px" },
        { label: "典型影院flare", value: "1.0%" },
        { label: "Callier修正", value: "1.0–1.4% density" },
        { label: "硬件Grain Manager", value: "Off" },
        { label: "共享乳剂随机实现", value: "是" },
      ] },
      { title: "数值验证与效率", items: [
        { label: "放映缓存格点", value: "193³ · exact analytical samples" },
        { label: "真实帧平均ΔE", value: "0.047–0.064 Oklab" },
        { label: "真实帧p99 ΔE", value: "0.307–0.359 Oklab" },
        { label: "逐像素放映加速", value: "约14×" },
        { label: "单帧双母版探测", value: "166.23秒（含封装与哈希）" },
        { label: "T020计算到第24帧", value: "3472.0秒 · 57分52秒" },
        { label: "T032计算到第24帧", value: "3551.5秒 · 59分11.5秒" },
        { label: "两段并行总等待", value: "约3551.5秒 · 59分11.5秒" },
        { label: "停止后整理", value: "T020 6.25秒 / T032 6.02秒", note: "无损取前24帧、补元数据、截图与哈希" },
        { label: "阶段计时", value: "未伪造", note: "原72帧任务在用户改为1秒时中止；内存中的阶段数组未落盘，只保留真实总墙钟" },
      ] },
    ],
  },
];

// V24 deliberately inherits the complete V23 parameter record and replaces
// only the measured texture terms. This keeps the side panel exhaustive while
// making it obvious that colour, tone, MTF and sensitometry were held fixed.
const v23 = versions[versions.length - 1];
v23.year = "上一版";
v23.status = "calibration";

const v24Overrides: Record<string, string> = {
  "颗粒相关尺度": "0.76",
  "五级占比": "0.16 / 0.30 / 0.32 / 0.17 / 0.05",
  "半径倍率": "0.50 / 0.68 / 0.86 / 1.08 / 1.34",
  "光学倍率": "0.68 / 0.80 / 0.92 / 1.05 / 1.18",
  "色度颗粒σ / 高频": "0.72 @ 2K / 0.30 · opponent 0.64",
  "真实帧平均ΔE": "与V23完全相同（平均颜色链未改）",
  "真实帧p99 ΔE": "与V23完全相同（平均颜色链未改）",
};

const v23TimingLabels = new Set([
  "单帧双母版探测", "T020计算到第24帧", "T032计算到第24帧",
  "两段并行总等待", "停止后整理", "阶段计时",
]);

const v24Parameters = (v23.parameters ?? []).map((group) => ({
  ...group,
  items: [
    ...group.items
      .filter((item) => group.title !== "数值验证与效率" || !v23TimingLabels.has(item.label))
      .map((item) => v24Overrides[item.label] ? { ...item, value: v24Overrides[item.label] } : item),
    ...(group.title === "扫描与放映输出" ? [
      { label: "放映色度颗粒积分", value: "σ 0.62 @ 2K · 高频0.36 · opponent 0.66" },
      { label: "颗粒平均色约束", value: "只作用于signed delta；均值分支不变" },
    ] : []),
    ...(group.title === "数值验证与效率" ? [
      { label: "V24 48µm RMS误差", value: "约0.6–1.4%" },
      { label: "T020综合色/明度颗粒", value: "放映1.58 → 0.93 · 扫描1.72 → 0.92" },
      { label: "T032综合色/明度颗粒", value: "放映2.07 → 1.15 · 扫描2.11 → 1.08" },
      { label: "V24平均颜色最大变化", value: "0.000000（数值精确不变）" },
      { label: "T020真实总墙钟", value: "3450.98秒 · 57分31秒" },
      { label: "T032真实总墙钟", value: "3511.76秒 · 58分32秒" },
      { label: "两段并行总等待", value: "3511.76秒 · 58分32秒" },
      { label: "乳剂形成 / 帧", value: "T020 77.53秒 · T032 77.60秒" },
      { label: "平均负片 / 帧", value: "31.58秒 · 32.67秒" },
      { label: "投影 / 扫描 / 帧", value: "约17.3秒 / 15.9–16.9秒" },
      { label: "解码 / 双路编码 / 帧", value: "约0.85–1.01秒 / 0.31–0.44秒" },
      { label: "性能瓶颈", value: "45组全画幅有限位点二项采样", note: "现场调用栈主要落在NumPy binomial；编码、解码与磁盘不是瓶颈" },
      { label: "现场硬件利用", value: "16核 / 48GB；采样时CPU约80%空闲", note: "参考实现未有效并行化最重随机步骤，不代表硬件弱" },
      { label: "网页观察空间", value: "sRGB IEC 61966-2-1 · D65", note: "静态图与短视频使用同一显示变换；5.7K 12-bit Rec.709母版保持不变" },
      { label: "网页帧对齐", value: "第13帧静态图 = 短视频首帧", note: "24帧循环重排为13–24、1–12，悬停切换不再跳画面" },
      { label: "网页Live预览", value: "1920 × 1440 · H.264 · 24fps · 1.001秒", note: "sRGB网页代理；逐片验证视频首帧与大图的综合色及中间调误差" },
    ] : []),
  ],
}));

versions.push({
  version: "V24",
  year: "当前版本",
  title: "35mm颗粒频谱与综合色分离",
  status: "current",
  projection: { src: "/versions/v24-t020-projection.jpg", videoSrc: "/versions/v24-t020-projection-live-srgb.mp4", label: "T020 · 5279 → 2383氙灯放映" },
  bluray: { src: "/versions/v24-t020-bluray.jpg", videoSrc: "/versions/v24-t020-bluray-live-srgb.mp4", label: "T020 · Period 2K / Cineon蓝光" },
  summary: "回应V23更像早期CCD或16mm的观感：V24不重调颜色，而是把公开的48µm RMS与完整空间频谱区分开。五级染料云向较小尺度重新分配，并在放映与扫描的观察阶段只积分综合色颗粒，保留明度颗粒的逐帧有机沸腾。平均色彩、黑白灰、负片MTF、2383与Cineon链均保持V23。",
  changes: ["染料云尺寸分布向35mm细颗粒端移动", "减少大云占比和总体相关尺度", "放映与扫描分别加入综合色颗粒积分", "完整保留明度颗粒与逐帧随机实现", "平均颜色与色调分支保持数值不变", "两段新素材继续各做1秒5.7K 12-bit双母版", "V24四个画面改为1秒Live网页预览，保留静帧放大与左右导航"],
  errors: ["V23虽然改善了离散颗粒形态，但综合色颗粒仍过强，容易被识别为RGB彩噪或早期CCD", "48µm RMS只约束特定孔径下的幅度，不能单独决定颗粒的粗细、低频成团和最终观看尺度", "公开文件没有5279完整Wiener/NPS曲线；V24的尺寸分布仍是受边界约束的模型选择，不是秘方复原", "黑白灰和创作调色没有在V24内重做；这样可以把颗粒判断与调色判断分离"],
  discoveries: ["35mm与16mm的显著差别不只是RMS大小，还包括放大倍率、低频功率与输出链MTF", "将颗粒做小后重新回标48µm RMS不会让它自动变安静，观察器对综合色与明度纹理的积分同样重要", "综合色颗粒可以在signed grain delta中独立处理，因此减少CCD感而不改变平均色相或饱和度", "T020与T032的综合色/明度颗粒比都显著下降，而平均输出的最大绝对差为零"],
  refs: ["R1", "R4", "R7", "R8", "R21", "R22", "R23", "R25"],
  additionalTrials: [{
    name: "NJARAW_S001_S001_T032",
    note: "雨天青绿和低反差细节用于验证综合色颗粒不会重新变成青绿色CCD噪声。",
    projection: { src: "/versions/v24-t032-projection.jpg", videoSrc: "/versions/v24-t032-projection-live-srgb.mp4", label: "T032 · 5279 → 2383氙灯放映" },
    bluray: { src: "/versions/v24-t032-bluray.jpg", videoSrc: "/versions/v24-t032-bluray-live-srgb.mp4", label: "T032 · Period 2K / Cineon蓝光" },
  }],
  parameters: v24Parameters,
});

const v24 = versions[versions.length - 1];
v24.year = "上一版";
v24.status = "calibration";

const v25Overrides: Record<string, string> = {
  "显示编码": "Rec.709 OETF · 完整1-1-1 · 两个监看分支一致",
  "随机种子": "逐帧/记录/速度/粒径/固定条带；线程数不改变结果",
  "颜色决定": "沿用V22已验证分析染料链；不采纳未识别hourly候选",
  "网页观察空间": "Rec.709反OETF后统一转sRGB D65",
};

const v25Parameters = (v24.parameters ?? []).map((group) => ({
  ...group,
  items: [
    ...group.items
      .filter((item) => group.title !== "数值验证与效率" || ![
        "T020真实总墙钟", "T032真实总墙钟", "两段并行总等待", "乳剂形成 / 帧",
        "平均负片 / 帧", "投影 / 扫描 / 帧", "解码 / 双路编码 / 帧", "网页观察空间",
        "网页帧对齐", "网页Live预览", "性能瓶颈", "现场硬件利用",
      ].includes(item.label))
      .map((item) => v25Overrides[item.label] ? { ...item, value: v25Overrides[item.label] } : item),
    ...(group.title === "扫描与放映输出" ? [
      { label: "放映监看母版", value: "Rec.709-D65 OETF · 1-1-1", note: "内部保留2383、氙灯、48 nit与gamma 2.6影院观察，再适配到Rec.709监视器" },
      { label: "蓝光母版", value: "Rec.709-D65 OETF · 1-1-1", note: "BT.1886是参考显示EOTF，不再把其反函数写进源文件" },
      { label: "影院观看条件", value: "48 cd/m² · gamma 2.6（投影观察模型内部）" },
      { label: "蓝光观看条件", value: "BT.1886 SDR参考显示" },
      { label: "母版范围", value: "full-range RGB计算 → 12-bit 4:4:4 ProRes" },
      { label: "网页代理", value: "sRGB IEC 61966-2-1 · D65" },
    ] : []),
    ...(group.title === "数值验证与效率" ? [
      { label: "V25修正一帧双母版", value: "79.77秒（含封装与哈希）" },
      { label: "V24等效一帧", value: "约143秒核心计算" },
      { label: "银盐采样 1→8线程", value: "70.09 → 35.22秒 · 1.99×" },
      { label: "线程一致性", value: "5760×4320逐像素相同 · max Δ 0" },
      { label: "复用平均负片", value: "删除每帧一次完整重复显影计算" },
      { label: "颗粒质量捷径", value: "无", note: "未减分辨率、未减45组采样、未缩短帧数、未改RMS/MTF/粒径" },
      { label: "错误版T020蓝光YAVG", value: "1354.70" },
      { label: "修正版T020蓝光YAVG", value: "1060.24", note: "V24基线1060.04；差异0.02%" },
      { label: "错误→修正YLOW", value: "557 → 304", note: "V24基线304" },
      { label: "正式T020计时", value: "1649.71秒 · 27分29.71秒" },
      { label: "正式T032计时", value: "1642.29秒 · 27分22.29秒" },
      { label: "两段并行总等待", value: "1649.71秒 · 27分29.71秒" },
      { label: "相对V24总等待", value: "58分32秒 → 27分30秒 · 缩短53.0%" },
      { label: "正式平均负片 / 帧", value: "T020 32.64秒 · T032 32.43秒" },
      { label: "正式乳剂形成 / 帧", value: "16.05秒 · 17.33秒", note: "八个固定条带worker；含完整二项抽样、DIR与RMS回标" },
      { label: "正式双观察器 / 帧", value: "18.71秒 · 16.82秒", note: "2383放映监看与Rec.709蓝光并行" },
      { label: "解码 / 双路编码 / 帧", value: "0.68–1.02秒 / 0.31–0.47秒" },
      { label: "网页首帧亮度误差", value: "0.00133–0.00164 median luma" },
      { label: "网页首帧RGB MAE", value: "0.00617–0.01436", note: "复用已验证的sRGB JPEG与H.264代理；全部低于验收阈值0.025" },
      { label: "Live代理", value: "1920 × 1440 · 24帧 · sRGB transfer" },
    ] : []),
  ],
}));

versions.push({
  version: "V25",
  year: "当前版本",
  title: "把观看条件与交换母版彻底分开",
  status: "current",
  projection: { src: "/versions/v25-t020-projection.jpg", videoSrc: "/versions/v25-t020-projection-live-srgb.mp4", label: "T020 · 2383影院观察的Rec.709监看" },
  bluray: { src: "/versions/v25-t020-bluray.jpg", videoSrc: "/versions/v25-t020-bluray-live-srgb.mp4", label: "T020 · Period 2K / Rec.709蓝光" },
  summary: "V25不重新调5279颜色，也不改变V24的颗粒、MTF、DIR、2383或扫描完成曲线。第一次V25误把观看条件当成源文件编码：蓝光写入BT.1886反函数，放映监看又被重编码成P3 gamma 2.6，导致普通播放器中间调与暗部过亮。修正版把两份监看母版统一恢复为Rec.709 OETF与完整1-1-1；影院gamma和BT.1886只留在各自观察/显示端。固定种子条带与平均负片复用的无降质加速完整保留。",
  changes: ["修正第一次V25整体提亮的OETF/EOTF错位", "放映分支明确为2383影院观察的Rec.709监看呈现", "蓝光母版恢复Rec.709 OETF与完整1-1-1", "BT.1886只作为参考显示EOTF，不再反写进母版码值", "T020蓝光YAVG由1354.70回到1060.24，V24基线1060.04", "网页大图与Live视频从Rec.709母版统一转换到sRGB", "45组银盐位点固定种子并行与平均负片复用完整保留", "hourly研究只保留已通过官方来源与真实素材验证的结论"],
  errors: ["第一次V25把BT.1886显示EOTF的反函数直接作为蓝光源文件编码，同时仍标记为Rec.709 1-1-1，播放器解释后造成约20–28%的平均码值提亮", "第一次V25把已经经过影院→Rec.709监看适配的2383分支再次转换到P3 gamma 2.6，混合了物理影院观察器与监看交换母版", "P3色度、ST 428 transfer与BT.709 YUV矩阵混写在ProRes中，跨播放器行为不稳定", "参考显示标准不能替代交换信号定义；母版标签、OETF和网页解码必须端到端一致", "公开资料仍不足以识别5279所有层间参数；toe、DLE、Spirit窄带候选和rem-jet残余项因此没有进入V25"],
  discoveries: ["用户看到的提亮不是主观错觉：T020蓝光YLOW从304变成557，说明暗部被显著抬起", "BT.1886定义显示端V→L，不等于Rec.709交换母版必须直接使用其反函数", "2383_projection_monitor已经包含影院到监视器的观察适配，不能再次当作物理P3银幕信号编码", "固定随机条带让并行度与画面内容解耦：1和8线程的全画幅密度数组完全相同", "hourly研究的价值也包括证伪：LAD单点、未公开扫描器光谱或单通道专利数据不足以授权全局颜色变化"],
  refs: ["R1", "R4", "R26", "R27", "R28", "R29", "R30", "R31", "R32"],
  additionalTrials: [{
    name: "NJARAW_S001_S001_T032",
    note: "雨天青绿、暗柱与低反差纹理用于检查两个Rec.709监看分支的黑位、gamma和标签一致性。",
    projection: { src: "/versions/v25-t032-projection.jpg", videoSrc: "/versions/v25-t032-projection-live-srgb.mp4", label: "T032 · 2383影院观察的Rec.709监看" },
    bluray: { src: "/versions/v25-t032-bluray.jpg", videoSrc: "/versions/v25-t032-bluray-live-srgb.mp4", label: "T032 · Period 2K / Rec.709蓝光" },
  }],
  parameters: v25Parameters,
});

const v25 = versions[versions.length - 1];
v25.year = "上一版";
v25.status = "calibration";

const v26Overrides: Record<string, string> = {
  "颜色决定": "V25修正基线完全锁定；V26不加入艺术调色",
  "显示编码": "Rec.709 OETF · 完整1-1-1 · 与V25修正版一致",
  "网页观察空间": "母版反Rec.709 OETF → sRGB IEC 61966-2-1",
};

const v26Parameters = (v25.parameters ?? []).map((group) => ({
  ...group,
  items: [
    ...group.items
      .filter((item) => group.title !== "数值验证与效率" || ![
        "V25修正一帧双母版", "V24等效一帧", "正式T020计时", "正式T032计时",
        "两段并行总等待", "相对V24总等待", "正式平均负片 / 帧", "正式乳剂形成 / 帧",
        "正式双观察器 / 帧", "错误版T020蓝光YAVG", "修正版T020蓝光YAVG", "错误→修正YLOW",
      ].includes(item.label))
      .map((item) => v26Overrides[item.label] ? { ...item, value: v26Overrides[item.label] } : item),
    ...(group.title === "乳剂颗粒" ? [
      { label: "快层五级权重", value: "0.12 · 0.26 · 0.34 · 0.20 · 0.08", note: "阴影/欠曝区以较大、较快晶体贡献为主" },
      { label: "中层五级权重", value: "0.16 · 0.30 · 0.32 · 0.17 · 0.05", note: "保持V24/V25已验证中心分布" },
      { label: "慢层五级权重", value: "0.22 · 0.34 · 0.29 · 0.12 · 0.03", note: "高光区减少大云尾部；不改变该记录48µm RMS" },
      { label: "时间模型", value: "每帧重新采样独立有限位点", note: "不移动、不循环、不平移一张噪点贴图" },
    ] : []),
    ...(group.title === "数值验证与效率" ? [
      { label: "V26颜色/曲线变化", value: "无", note: "V25负片均值、MTF、DIR、2383、扫描器、黑位与Gamma全部锁定" },
      { label: "T020蓝光首帧YAVG", value: "V25 1060.24 → V26 1060.33", note: "变化0.09 / 4095；来自零均值随机实现" },
      { label: "T032蓝光首帧YAVG", value: "V25 1356.63 → V26 1356.73", note: "变化0.10 / 4095" },
      { label: "T020 / T032首帧YLOW", value: "304 / 281 · 与V25一致" },
      { label: "最大帧间lag-1相关", value: "0.0074", note: "均匀曝光四帧、三记录；接近独立随机场" },
      { label: "最大平均密度漂移", value: "0.00015 D", note: "四帧均匀曝光诊断；没有系统性色偏" },
      { label: "阴影快层颗粒功率", value: "约61–65%" },
      { label: "高光慢层颗粒功率", value: "约50–59%" },
      { label: "正式T020计时", value: "1894.14秒 · 31分34.14秒" },
      { label: "正式T032计时", value: "1893.93秒 · 31分33.93秒" },
      { label: "两段并行总等待", value: "1894.14秒 · 31分34.14秒" },
      { label: "平均负片 / 帧", value: "T020 36.60秒 · T032 36.64秒" },
      { label: "随机乳剂 / 帧", value: "18.17秒 · 19.21秒" },
      { label: "双观察器 / 帧", value: "21.66秒 · 20.11秒" },
      { label: "插件准备结论", value: "97%+核心时间适合GPU迁移", note: "Resolve 2026 OpenFX SDK已验证Metal/CUDA/OpenCL路径；当前参考实现仍是CPU" },
      { label: "输出", value: "两段各24帧 · 5760×4320 · 12-bit ProRes 4444 · 双母版" },
    ] : []),
  ],
}));

versions.push({
  version: "V26",
  year: "当前版本",
  title: "让曝光选择颗粒频谱，而不是只改变颗粒响度",
  status: "current",
  projection: { src: "/versions/v26-t020-projection.jpg", videoSrc: "/versions/v26-t020-projection-live-srgb.mp4", label: "T020 · 2383影院观察的Rec.709监看" },
  bluray: { src: "/versions/v26-t020-bluray.jpg", videoSrc: "/versions/v26-t020-bluray-live-srgb.mp4", label: "T020 · Period 2K / Rec.709蓝光" },
  summary: "V26完全锁住V25修正版的色彩、黑位、对比、Gamma和Rec.709 1-1-1输出，只修正乳剂内部一个被简化的地方：快、中、慢三层不再共用同一套五级染料云权重。阴影由更大、更快的晶体统计主导，高光由更细的慢层主导；每个曝光和颜色记录仍重新回标5279公开的48µm扩散RMS，所以变化是颗粒空间频谱与有机运动，而不是更响的噪点。",
  changes: ["将五级染料云分布从全层共享改为快/中/慢三套权重", "阴影保留较宽的大云尾部，高光减少大云尾部", "每帧独立采样有限银盐位点，保持有机沸腾且不形成移动噪点贴图", "5279三记录48µm RMS继续作为最终振幅约束", "V25颜色、黑白灰、MTF、DIR、2383与Period 2K观察器逐项锁定", "首帧亮度和黑位数值回归通过", "加入NPS、层激活、均值漂移与帧间相关诊断", "T020与T032继续各交付1秒5.7K 12-bit双母版", "建立Resolve OFX迁移性能合同与Metal优先架构"],
  errors: ["V25的三速度层已有不同基础半径，但每层内部仍共用同一个五级尺寸分布", "共享分布会让慢层在高光中保留与快层相同的大云尾部，削弱35mm应有的曝光相关细腻变化", "仅用48µm RMS无法唯一决定颗粒观感；同一积分振幅可对应不同空间频谱", "5279没有公开逐亚层完整Wiener/NPS与涂布配方，因此V26权重是由Kodak机制约束的保守模型，不宣称是秘方复原"],
  discoveries: ["Kodak明确指出高速感光晶体通常最大，并在阴影或欠曝光处更明显", "三层噪声功率随p(1-p)而变化：阴影测试中快层约占61–65%，高光中慢层约占50–59%", "V26的高光有效颗粒半径下降，而阴影略向低频移动；总体48µm RMS不变", "四帧均匀场最大lag-1相关约0.0074，支持逐帧独立显影事件而非动画噪点", "T020/T032蓝光首帧YAVG相对V25仅变化0.09/0.10个12-bit码值，黑位不变"],
  refs: ["R1", "R7", "R21", "R23", "R25", "R33"],
  additionalTrials: [{
    name: "NJARAW_S001_S001_T032",
    note: "雨天青绿、暗柱、高光树叶与低反差纹理用于验证三速度层切换不会带来色相漂移或CCD式综合色噪点。",
    projection: { src: "/versions/v26-t032-projection.jpg", videoSrc: "/versions/v26-t032-projection-live-srgb.mp4", label: "T032 · 2383影院观察的Rec.709监看" },
    bluray: { src: "/versions/v26-t032-bluray.jpg", videoSrc: "/versions/v26-t032-bluray-live-srgb.mp4", label: "T032 · Period 2K / Rec.709蓝光" },
  }],
  parameters: v26Parameters,
});

const v26 = versions[versions.length - 1];
v26.year = "上一版";
v26.status = "calibration";

const groupTitlesEn: Record<string, string> = {
  "输入与母版": "INPUT & MASTERS",
  "5279乳剂": "5279 EMULSION",
  "5279乳剂与颗粒": "5279 EMULSION & GRAIN",
  "乳剂颗粒": "EMULSION GRAIN",
  "DIR显影耦合": "DIR DEVELOPMENT COUPLING",
  "2383放映链": "2383 PROJECTION CHAIN",
  "染料与2383放映": "DYES & 2383 PROJECTION",
  "显示器放映预览": "PROJECTION MONITOR VIEW",
  "Period 2K / 蓝光": "PERIOD 2K / BLU-RAY",
  "扫描与放映输出": "SCAN & PROJECTION OUTPUT",
  "数值验证与效率": "NUMERICAL VALIDATION & PERFORMANCE",
};

const parameterLabelsEn: Record<string, string> = {
  "源素材": "Source footage", "源素材 A": "Source A", "源素材 B": "Source B",
  "RAW解码": "RAW decode", "相机色彩": "Camera colour", "相机 / 记录": "Camera / record transform",
  "拍摄参数": "Capture settings", "虚拟曝光": "Virtual exposure", "画幅": "Frame", "画幅 / 帧率": "Frame / rate",
  "帧率": "Frame rate", "测试段": "Test segment", "每段长度": "Length per source", "母版": "Master",
  "显示编码": "Signal encoding", "片种": "Film stock", "片种 / 成像宽": "Stock / image width", "假定成像宽": "Assumed image width",
  "亚层结构": "Sublayer structure", "速度偏移": "Speed offsets", "容量比例 快/中/慢": "Capacity fast/mid/slow",
  "快层中心 R/G/B": "Fast centres R/G/B", "转折宽度 R/G/B": "Transition widths R/G/B",
  "ECD 青记录": "ECD cyan record", "ECD 品红记录": "ECD magenta record", "ECD 黄记录": "ECD yellow record",
  "颗粒校准孔径": "Grain calibration aperture", "颗粒校准": "Grain calibration", "颗粒相关尺度": "Grain correlation scale",
  "粒径占比": "Size fractions", "五级占比": "Five-class fractions", "粒径半径倍率": "Radius factors", "半径倍率": "Radius factors",
  "光学倍率": "Optical factors", "亚像素相位半径": "Subpixel phase radius", "相位步进": "Phase step",
  "光学σ 青记录": "Optical σ cyan", "光学σ 品红记录": "Optical σ magenta", "光学σ 黄记录": "Optical σ yellow",
  "有效位点 青记录": "Effective sites cyan", "有效位点 品红记录": "Effective sites magenta", "有效位点 黄记录": "Effective sites yellow",
  "负片MTF σ R/G/B": "Negative MTF σ R/G/B", "正片MTF σ R/G/B": "Print MTF σ R/G/B",
  "感色重叠 Row R": "Sensitivity overlap row R", "感色重叠 Row G": "Sensitivity overlap row G", "感色重叠 Row B": "Sensitivity overlap row B",
  "随机种子": "Random seed", "传感器噪声": "Sensor-noise treatment", "发生阶段": "Domain", "DIR阶段": "DIR domain",
  "扩散σ 快/中/慢": "Diffusion σ fast/mid/slow", "DIR扩散σ": "DIR diffusion σ", "层间强度": "Interlayer strength",
  "层内强度 R/G/B": "Intralayer strength R/G/B", "随机耦合": "Stochastic coupling",
  "释放增益 快/中/慢": "Release gain fast/mid/slow", "接收增益 快/中/慢": "Receiver gain fast/mid/slow",
  "传输矩阵 Row 1": "Transport matrix row 1", "传输矩阵 Row 2": "Transport matrix row 2", "传输矩阵 Row 3": "Transport matrix row 3",
  "中性约束": "Neutral constraint", "正片": "Print stock", "Status-A D-min R/G/B": "Status-A D-min R/G/B",
  "LAD目标": "LAD aim", "LAD目标 / D-max": "LAD aim / D-max", "D-max": "D-max", "印片光": "Printer light",
  "放映光": "Projection light", "印片 / 放映光": "Printer / projection light", "Callier修正": "Callier correction",
  "典型影院flare": "Typical cinema flare", "层间矩阵 Row 1": "Interimage matrix row 1", "层间矩阵 Row 2": "Interimage matrix row 2", "层间矩阵 Row 3": "Interimage matrix row 3",
  "物理亮度权重": "Physical-lightness weight", "最大物理色相权重": "Maximum physical-hue weight", "最大物理饱和权重": "Maximum physical-saturation weight",
  "色度校准": "Chroma calibration", "显示色度校准": "Display chroma calibration", "校准格点": "Calibration lattice", "相对色度格点": "Relative-chroma lattice",
  "中性保护": "Neutral guard", "插值余量": "Interpolation margin", "扫描亮度锚点": "Scan-luma anchors", "目标亮度锚点": "Target-luma anchors",
  "色域映射": "Gamut mapping", "扫描观察器": "Scan observer", "扫描孔径": "Scan aperture", "Cineon": "Cineon mapping",
  "中性灰码值": "Neutral-gray code", "主色校正强度": "Primary-correction strength", "肩部释放": "Shoulder release",
  "蓝光下段gamma": "Blu-ray lower-scale gamma", "色度颗粒σ": "Chroma-grain σ", "色度颗粒σ / 高频": "Chroma grain σ / high-frequency retention",
  "高频色度保留": "High-frequency chroma retention", "硬件Grain Manager": "Hardware Grain Manager", "共享乳剂随机实现": "Shared emulsion realization",
  "颜色决定": "Colour decision", "放映缓存格点": "Projection cache lattice", "真实帧平均ΔE": "Real-frame mean ΔE", "真实帧p99 ΔE": "Real-frame p99 ΔE",
  "逐像素放映加速": "Per-pixel projection speed-up", "放映色度颗粒积分": "Projection chroma-grain integration", "颗粒平均色约束": "Grain mean-colour constraint",
  "V24 48µm RMS误差": "V24 48 µm RMS error", "T020综合色/明度颗粒": "T020 opponent/luma grain", "T032综合色/明度颗粒": "T032 opponent/luma grain",
  "V24平均颜色最大变化": "V24 maximum mean-colour change", "银盐采样 1→8线程": "Silver-site sampling, 1→8 workers", "线程一致性": "Worker invariance",
  "复用平均负片": "Mean-negative reuse", "颗粒质量捷径": "Grain quality shortcuts", "网页观察空间": "Web viewing space", "网页首帧亮度误差": "Web first-frame luma error",
  "网页首帧RGB MAE": "Web first-frame RGB MAE", "Live代理": "Live proxy", "放映监看母版": "Projection monitor master", "蓝光母版": "Blu-ray master",
  "影院观看条件": "Cinema viewing condition", "蓝光观看条件": "Blu-ray viewing condition", "母版范围": "Master range", "网页代理": "Web proxy",
  "V26颜色/曲线变化": "V26 colour / curve change", "T020蓝光首帧YAVG": "T020 Blu-ray first-frame YAVG", "T032蓝光首帧YAVG": "T032 Blu-ray first-frame YAVG",
  "T020 / T032首帧YLOW": "T020 / T032 first-frame YLOW", "最大帧间lag-1相关": "Maximum frame lag-1 correlation", "最大平均密度漂移": "Maximum mean-density drift",
  "阴影快层颗粒功率": "Shadow fast-layer grain power", "高光慢层颗粒功率": "Highlight slow-layer grain power",
  "快层五级权重": "Fast-layer five-class weights", "中层五级权重": "Medium-layer five-class weights", "慢层五级权重": "Slow-layer five-class weights", "时间模型": "Temporal model",
  "平均负片 / 帧": "Mean negative / frame", "随机乳剂 / 帧": "Stochastic emulsion / frame", "双观察器 / 帧": "Two observers / frame",
  "插件准备结论": "Plugin readiness", "输出": "Output",
};

const exactValueEnglish: Record<string, string> = {
  "Panasonic官方RAW → V-Gamut": "Panasonic official RAW → V-Gamut",
  "R/G/B × 快/中/慢 × 5粒径": "R/G/B × fast/mid/slow × five size classes",
  "2.399963 rad · 黄金角": "2.399963 rad · golden angle",
  "逐帧、逐记录、逐速度群独立": "Independent per frame, record and speed population",
  "九亚层合并前的显影域": "Development domain before the nine sublayers merge",
  "均匀H-D严格不漂移": "Exact uniform H-D invariance",
  "D-min已扣除的带符号净光谱密度": "Signed net spectral density with D-min subtracted",
  "非线性Status-A积分反演": "Nonlinear inversion of integral Status-A density",
  "3200 K / Kodak氙灯SPD": "3200 K / Kodak xenon SPD",
  "D60相对Oklab a/b · L不变": "Relative D60 OKLab a/b · L unchanged",
  "Oklab恒色相压缩": "OKLab constant-hue compression",
  "Spirit式宽带RGB · 620/540/470 nm": "Spirit-like broadband RGB · 620/540/470 nm",
  "只作用于signed delta；均值分支不变": "Signed delta only; deterministic mean branch unchanged",
  "放映1.58 → 0.93 · 扫描1.72 → 0.92": "Projection 1.58 → 0.93 · scan 1.72 → 0.92",
  "放映2.07 → 1.15 · 扫描2.11 → 1.08": "Projection 2.07 → 1.15 · scan 2.11 → 1.08",
  "0.000000（数值精确不变）": "0.000000 (numerically exact)",
  "45组全画幅有限位点二项采样": "45 full-frame finite-site binomial populations",
  "16核 / 48GB；采样时CPU约80%空闲": "16 cores / 48 GB; ~80% CPU idle during sampling",
  "第13帧静态图 = 短视频首帧": "Frame 13 still = live-preview first frame",
  "Rec.709-D65 OETF · 1-1-1": "Rec.709-D65 OETF · 1-1-1",
  "48 cd/m² · gamma 2.6（投影观察模型内部）": "48 cd/m² · gamma 2.6 (inside the projection observer)",
  "BT.1886 SDR参考显示": "BT.1886 SDR reference display",
  "full-range RGB计算 → 12-bit 4:4:4 ProRes": "Full-range RGB computation → 12-bit 4:4:4 ProRes",
  "5760×4320逐像素相同 · max Δ 0": "5760×4320 pixel-identical · max Δ 0",
  "删除每帧一次完整重复显影计算": "One duplicate full development pass removed per frame",
  "每帧重新采样独立有限位点": "Fresh independent finite-site sampling every frame",
  "97%+核心时间适合GPU迁移": "97%+ of core time is suitable for GPU migration",
};

const valueToEnglish = (value: string) => exactValueEnglish[value] ?? value
  .replaceAll("约", "~")
  .replaceAll("秒", "s")
  .replaceAll("分钟", "min")
  .replaceAll("分", "m")
  .replaceAll("帧", " frames")
  .replaceAll("两段各", "each of two sources: ")
  .replaceAll("无", "None")
  .replaceAll("是", "Yes")
  .replaceAll("与V25一致", "same as V25")
  .replaceAll("与V25修正版一致", "same as corrected V25");

const v27Parameters = (v26.parameters ?? []).map((group) => ({
  ...group,
  titleEn: groupTitlesEn[group.title] ?? group.title,
  items: [
    ...group.items
      .filter((item) => group.title !== "数值验证与效率" || ![
        "正式T020计时", "正式T032计时", "两段并行总等待", "平均负片 / 帧",
        "随机乳剂 / 帧", "双观察器 / 帧", "V26颜色/曲线变化",
      ].includes(item.label))
      .map((item) => ({
        ...item,
        labelEn: parameterLabelsEn[item.label] ?? item.label,
        valueEn: valueToEnglish(item.value),
      })),
    ...(group.title === "扫描与放映输出" ? [
      { label: "V27扫描灰轴", labelEn: "V27 scan gray axis", value: "2049级中性曝光 · 密度相关RGB平衡", valueEn: "2049-level neutral exposure scale · level-dependent RGB balance" },
      { label: "亮度约束", labelEn: "Luminance constraint", value: "逐像素Rec.709 Y严格保持", valueEn: "Exact per-pixel Rec.709 Y preservation", note: "不改变黑位、对比度、下段gamma或高光亮度", noteEn: "No change to black, contrast, lower-scale gamma or highlight luminance" },
      { label: "Period 2K孔径", labelEn: "Period 2K aperture", value: "与V26完全相同", valueEn: "Unchanged from V26" },
      { label: "2383放映母版", labelEn: "2383 projection master", value: "逐字节复用V26", valueEn: "Byte-identical reuse of V26" },
    ] : []),
    ...(group.title === "数值验证与效率" ? [
      { label: "中性通道最大残差", labelEn: "Maximum neutral-channel residual", value: "0.01820 → 0.00236", valueEn: "0.01820 → 0.00236" },
      { label: "中性通道p95残差", labelEn: "p95 neutral-channel residual", value: "0.01673 → 0.00166", valueEn: "0.01673 → 0.00166" },
      { label: "绿色对手最大残差", labelEn: "Maximum green-opponent residual", value: "0.02172 → 0.00242", valueEn: "0.02172 → 0.00242" },
      { label: "最大亮度漂移", labelEn: "Maximum luminance drift", value: "1.79 × 10⁻⁷", valueEn: "1.79 × 10⁻⁷" },
      { label: "放映分支最大漂移", labelEn: "Maximum projection drift", value: "0.000000", valueEn: "0.000000" },
      { label: "Hourly研究进入模型", labelEn: "Hourly research entering model", value: "仅证据边界；不改颗粒、DIR或NPS", valueEn: "Evidence boundary only; no grain, DIR or NPS change" },
      { label: "正式T020扫描计时", labelEn: "Formal T020 scan time", value: "25分47.08秒", valueEn: "25m 47.08s", note: "末3帧与T032并行，计时包含母版定稿与静帧写入，不含随后SHA-256", noteEn: "Last three frames overlapped T032; includes master finalization and still export, excludes later SHA-256 hashing" },
      { label: "正式T032扫描计时", labelEn: "Formal T032 scan time", value: "25分09.09秒", valueEn: "25m 09.09s", note: "前3帧与T020并行，计时包含母版定稿与静帧写入，不含随后SHA-256", noteEn: "First three frames overlapped T020; includes master finalization and still export, excludes later SHA-256 hashing" },
      { label: "输出", labelEn: "Output", value: "两段各24帧 · 5760×4320 · 12-bit ProRes 4444 · 双母版", valueEn: "24 frames per source · 5760×4320 · 12-bit ProRes 4444 · two masters" },
    ] : []),
  ],
}));

versions.push({
  version: "V27",
  year: "当前版本",
  title: "把扫描器的绿色罩层从胶片颜色中分离出来",
  status: "current",
  projection: { src: "/versions/v27-t020-projection.jpg", videoSrc: "/versions/v27-t020-projection-live-srgb.mp4", label: "T020 · 2383影院观察的Rec.709监看（与V26相同）" },
  bluray: { src: "/versions/v27-t020-bluray.jpg", videoSrc: "/versions/v27-t020-bluray-live-srgb.mp4", label: "T020 · 中性灰阶约束的Period 2K / Rec.709蓝光" },
  summary: "V27确认V26蓝光版的朦胧绿色并非网页或颗粒造成，而是扫描观察器只在18%灰与一个高密度点校准后留下的密度相关灰轴误差。新版本以2049级中性曝光建立扫描RGB平衡，并逐像素恢复原Rec.709亮度，因此绿色残差下降，但黑位、对比、Gamma、2K孔径与高光亮度不动。V26负片、颗粒、DIR、2383和放映母版全部锁定。",
  changes: ["用完整中性曝光尺度替代扫描器的双锚点灰平衡", "在完成的Period 2K扫描分支中加入密度相关RGB校准", "逐像素保持Rec.709亮度，禁止校准变成调色", "中性通道最大残差从0.01820降至0.00236", "绿色对手残差从0.02172降至0.00242", "否决会让真实RAW更绿、更亮的完全主色分离方案", "V26颗粒、DIR、NPS、MTF、黑位和Gamma全部锁定", "2383放映母版逐字节复用V26", "结合最新hourly研究的不可识别性结论，不凭专利编号或48µm RMS发明新参数", "核对2003年5279临时专利原件：确认编号沿革，但仍无任何5279数值参数", "网站加入完整中英文切换并保存语言选择"],
  errors: ["V26扫描器只在18%灰和一个高密度点定标，无法保证整条灰阶中性", "V26人为保留18%的所谓Spirit/染料残余，但公开资料没有支持其色相和密度形状", "阴影和低中间调出现绿色隆起，中灰锚点正确，亮部偏移方向又改变，所以全局品红无法修复", "2K孔径的柔化与RGB灰轴错误曾在观感上混成同一种绿色雾感", "最新hourly研究仍没有公开5279专属NPS、DIR矩阵或Spirit私有校准，不能借V27改写这些部分"],
  discoveries: ["用户观察到的绿色罩层可以在中性尺度上重复测量", "网页Rec.709到sRGB转换对三通道一致，且放映版共用同一路径，因此不是网页ICC问题", "灰轴误差随密度改变方向，必须使用水平相关校准而不是一个白平衡旋钮", "保持每个像素的Rec.709 Y，可以把扫描色彩校准和艺术对比选择严格分开", "完全清除模拟扫描器串扰会改变亮度并让实拍植物更绿，说明更激进不等于更准确", "2003年4月临时专利确实把identifier 3写成5279；同年5月JVT-H022改成5218，后续专利又回到5279，属于文档分支漂移而不是胶片测量", "hourly研究的主要贡献是限制模型自由度：没有可识别证据的颗粒和DIR参数必须保持不变"],
  refs: ["R1", "R8", "R11", "R26", "R27", "R34", "R35", "R36", "R38", "R39", "R40", "R41"],
  additionalTrials: [{
    name: "NJARAW_S001_S001_T032",
    note: "雨天青绿、暗柱与低反差纹理用于确认灰轴校准不会把真实绿色错误拉回中性，也不会改变黑位和亮度。",
    projection: { src: "/versions/v27-t032-projection.jpg", videoSrc: "/versions/v27-t032-projection-live-srgb.mp4", label: "T032 · 2383影院观察的Rec.709监看（与V26相同）" },
    bluray: { src: "/versions/v27-t032-bluray.jpg", videoSrc: "/versions/v27-t032-bluray-live-srgb.mp4", label: "T032 · 中性灰阶约束的Period 2K / Rec.709蓝光" },
  }],
  parameters: v27Parameters,
});

export const references = [
  { id: "R1", title: "KODAK VISION 500T 5279 / 7279 Technical Data, H-1-5279t", type: "Kodak片种数据", url: "https://125px.com/docs/motionpicture/kodak/5279.pdf" },
  { id: "R2", title: "Exploring the Color Image", type: "Kodak技术读物", url: "https://www.kodak.com/content/products-brochures/Film/Exploring-the-Color-Image.pdf" },
  { id: "R3", title: "Processing KODAK Motion Picture Films, Module 7: ECN-2", type: "Kodak处理规范", url: "https://www.kodak.com/content/products-brochures/Film/Processing-KODAK-Motion-Picture-Films-Module-7.pdf" },
  { id: "R4", title: "KODAK VISION Color Print Film 2383 / 3383 Technical Data", type: "Kodak正片数据", url: "https://www.kodak.com/content/products-brochures/Film/VISION-Color-Print-Film-2383-3383-TECHNICAL-DATA.pdf" },
  { id: "R5", title: "LAD — Laboratory Aim Density, KODAK H-61", type: "Kodak实验室控制", url: "https://www.kodak.com/content/products-brochures/Film/LAD-Laboratory-Aim-Density.pdf" },
  { id: "R6", title: "US 5,298,376 — DIR inhibitor transport and colour saturation", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5298376A/en" },
  { id: "R7", title: "US 5,314,793 — multilayer speed and granularity architecture", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5314793A/en" },
  { id: "R8", title: "Spirit DataCine / Spirit HD technical data", type: "DFT扫描器资料", url: "https://www.dft-film.com/downloads/datasheets/DFT-Spirit-HD-datasheet-11-09.pdf" },
  { id: "R9", title: "Digital Intermediates, August 2003", type: "同期后期制作报道", url: "https://www.postmagazine.com/Publications/Post-Magazine/2003/August-1-2003/DIGITAL-INTERMEDIATES.aspx" },
  { id: "R10", title: "Charlie’s Angels: Full Throttle — technical specifications", type: "完成态参考", url: "https://www.imdb.com/title/tt0305357/technical/" },
  { id: "R11", title: "US 5,500,316 — colour negative contrast adjusted for electronic scanning", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5500316A/en" },
  { id: "R12", title: "US 5,705,327 — nonlinear curve shape for telecine transfer", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US5705327A/en" },
  { id: "R13", title: "The Chemistry of Kodak Film — Smarter Every Day 275-C", type: "柯达工厂访谈", url: "https://www.youtube.com/watch?v=zJ8aNPStQ8M" },
  { id: "R14", title: "Kodak’s Film Quality Control Process — 275-B", type: "柯达工厂质控", url: "https://www.youtube.com/watch?v=VIH0dEMyv9w" },
  { id: "R15", title: "Advanced Emulsion: crystals, couplers, masks and processing", type: "Kodak资料支持的讲解", url: "https://www.youtube.com/watch?v=I4_7tW-cx1I" },
  { id: "R16", title: "Digital Color Management for Motion Picture Film", type: "IS&T / Ado Ishii, 2003", url: "https://library.imaging.org/admin/apis/public/api/ist/website/downloadArticle/cic/11/1/art00055" },
  { id: "R17", title: "US 2002/0118211 — analytical dye density and interimage measurement", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US20020118211A1/en" },
  { id: "R18", title: "US 8,654,192 — LAD-anchored print-exposure matrix", type: "Adobe Systems专利", url: "https://patents.google.com/patent/US8654192B2/en" },
  { id: "R19", title: "Common LUT Format implementation guide", type: "ACES规范", url: "https://docs.acescentral.com/clf/guides/" },
  { id: "R20", title: "ISO 5-3:2009 — Photography and graphic technology: Spectral conditions", type: "ISO标准索引", url: "https://www.iso.org/standard/52915.html" },
  { id: "R21", title: "The Essential Reference Guide for Filmmakers", type: "Kodak电影胶片参考指南", url: "https://www.kodak.com/content/products-brochures/Film/kodak-essential-reference-guide-for-filmmakers.pdf" },
  { id: "R22", title: "Noise Power Spectra of Photographic Dye Images", type: "IS&T影像结构研究（反转片，仅作形态先验）", url: "https://library.imaging.org/admin/apis/public/api/ist/website/downloadArticle/print4fab/22/1/art00038_2" },
  { id: "R23", title: "US 4,536,472 — dye-cloud diffusion, Wiener spectrum and low-frequency mottle", type: "Eastman Kodak专利", url: "https://patents.google.com/patent/US4536472A/en" },
  { id: "R24", title: "EP 0,905,561 — speed-layer coupler coverage and spectrally differentiated dye records", type: "Eastman Kodak扫描型负片专利（非5279配方）", url: "https://patents.google.com/patent/EP0905561A1/en" },
  { id: "R25", title: "Print Grain Index — An Assessment of Print Graininess from Color Negative Films, E-58", type: "Kodak技术资料（2000年7月）", url: "https://125px.com/docs/techpubs/kodak/e58-2000_07.pdf" },
  { id: "R26", title: "ITU-R BT.709 — HDTV production and programme exchange", type: "ITU视频色度与信号标准", url: "https://www.itu.int/rec/R-REC-BT.709" },
  { id: "R27", title: "ITU-R BT.1886 — HDTV studio display EOTF", type: "ITU SDR参考显示标准", url: "https://www.itu.int/rec/R-REC-BT.1886" },
  { id: "R28", title: "Digital Cinema System Specification", type: "DCI数字影院规范", url: "https://www.dcimovies.com/dci-specification/" },
  { id: "R29", title: "CSS Color Module Level 4 — sRGB and web colour", type: "W3C网页颜色标准", url: "https://www.w3.org/TR/css-color-4/" },
  { id: "R30", title: "ACES 2 Output Transform parameters and display encodings", type: "Academy色彩管理规范", url: "https://docs.acescentral.com/system-components/output-transforms/parameters/" },
  { id: "R31", title: "ITU-R BT.1886-0 — Reference electro-optical transfer function", type: "ITU官方公式与黑白端点定义", url: "https://www.itu.int/dms_pubrec/itu-r/rec/bt/r-rec-bt.1886-0-201103-i%21%21pdf-e.pdf" },
  { id: "R32", title: "DCI Compliance Test Plan — calibrated screen luminance 48 cd/m²", type: "DCI影院白场测试条件", url: "https://ctp.dcimovies.com/0b5699a0b76a57547576565b89fd052467c8ac20/ctp.html" },
  { id: "R33", title: "US 6,815,153 — improved speed and granularity in high-speed colour negative film", type: "Eastman Kodak专利（分层机制，不是5279配方）", url: "https://patents.google.com/patent/US6815153B2/en" },
  { id: "R34", title: "US 6,190,847 — Kodak DIR diffusion-factor assay", type: "Eastman Kodak专利（测量机制，不是5279常数）", url: "https://patents.google.com/patent/US6190847B1/en" },
  { id: "R35", title: "EP 1,016,902 — green-only ECN-2 exposure as an interimage exclusion control", type: "Eastman Kodak专利（实验逻辑）", url: "https://data.epo.org/publication-server/rest/v1.2/publication-dates/20000705/patents/EP1016902NWA2/document.pdf" },
  { id: "R36", title: "Process ECN-2, H-24 processing modules", type: "Kodak处理与控制文件", url: "https://www.kodak.com/en/motion/page/processing-manuals/" },
  { id: "R37", title: "ISO 5-3 density spectral conditions and aperture dependence", type: "摄影密度测量标准", url: "https://www.iso.org/standard/52915.html" },
  { id: "R38", title: "US 7,899,113 — film-grain simulation identifiers and model database", type: "Thomson专利（5279条目无公开参数）", url: "https://patents.google.com/patent/US7899113B2/en" },
  { id: "R39", title: "JVT-H022 — SEI message for film grain encoding", type: "ITU JVT一手技术提案", url: "https://www.itu.int/wftp3/av-arch/jvt-site/2003_05_Geneva/JVT-H022.zip" },
  { id: "R40", title: "JVT-I013r2 — film grain encoding syntax and results", type: "ITU JVT一手技术提案", url: "https://www.itu.int/wftp3/av-arch/jvt-site/2003_09_SanDiego/JVT-I013r2.zip" },
  { id: "R41", title: "US provisional 60/462,389 — A Method for Simulating Film Grain on Encoded Video Sequences", type: "2003年原始临时专利（5279编号沿革，无数值参数）", url: "https://register.epo.org/application?documentId=EICL6DDCDHELFI4&number=EP04714129&lng=en&npl=false" },
];

export const refMap = Object.fromEntries(references.map((ref) => [ref.id, ref]));
