const siteCode = `p = sigmoid((logE - speed_centre) / transition_width)
developed = binomial(finite_sites, p) / finite_sites
density_delta = optical_integrate(developed - p, dye_cloud_kernel)
# sample changes every frame; conditional mean does not drift`;

const dirCode = `release = blur(population_density, lateral_sigma) - population_density
transport = population_matrix @ release
population_density += receiver_gain * transport
# uniform exposure produces zero local correction`;

const scanCode = `T = 10 ** (-spectral_density)
sensor_2k = area_integrate(scanner_response * T, width=2048)
D = -log10(sensor_2k / clear_reference)
cineon = 95 + (D - Dmin) / 0.002`;

const neutralCode = `neutral_scale = render_scan(scene_linear=geomspace(1e-5, 10, 2049))
rgb_balance = fit_level_dependent_balance(neutral_scale)
corrected = rgb_balance(display_linear)
corrected *= rec709_y(display_linear) / rec709_y(corrected)
# black, gamma and per-pixel luminance remain unchanged`;

const productionCode = `# V35 Production: keep the complete uint32 random word
threshold = floor(float32(probability) * 2**32)
developed += philox_u32(counter(frame, record, population,
                                size_class, x, y, lane)) < threshold
# all 45 identities per frame must be unique; V34 remains Archive exact`;

const stablePhaseCode = `# V37: frame remains in Philox identity; every frame is new emulsion
sampled_phase = rng.uniform(0, 2*pi)       # consume to preserve Archive sequence
class_id = record * 15 + population * 5 + size_class
phase = 2*pi * frac((class_id + 0.5) * golden_ratio) + pi/6
offset = 0.38 * [cos(phase), sin(phase)]
# only integration phase is stable; grain sites are never reused across frames`;

const deliveryCode = `# V38: Lobs is completed display-linear observer light
professional = pow(Lobs, 1/2.4)       # inverse ideal-black BT.1886
quicktime    = srgb_oetf(Lobs)        # explicit Mac viewing companion
still        = frame(quicktime, 12)   # no second OETF inversion
web_video    = encode_srgb(quicktime) # same first frame and transfer
# Decode(professional) ~= Decode(quicktime) ~= Lobs`;

export function AlgorithmEnglish() {
  return (
    <main className="algorithm-page wrap">
      <header className="page-header"><span className="eyebrow">METHOD · CURRENT V38</span><h1>Not a filter.<br />An image-formation chain.</h1><p>V38 freezes the complete V37 film image and corrects only the transfer boundary from observer-linear light into professional, QuickTime, still and web delivery.</p></header>

      <section className="pipeline"><div className="pipeline-line"><span>01<b>GH7 RAW</b><small>extended-linear RGB</small></span><i>→</i><span>02<b>Virtual exposure</b><small>V-Gamut / film records</small></span><i>→</i><span>03<b>5279 development</b><small>sites · dyes · DIR</small></span><i>→</i><span>04<b>Observer</b><small>2383 or 2K DI</small></span><i>→</i><span>05<b>Display delivery</b><small>BT.1886 master / sRGB companion</small></span></div></section>

      <section className="method-section"><div className="method-index">V38</div><div className="method-copy"><span className="section-tag">ONE OBSERVER LIGHT · TWO EXPLICIT DELIVERIES</span><h2>Code values may differ; decoded light must agree</h2><p>V37 stills exactly inverted the BT.709 OETF before sRGB encoding, while ProRes treated already completed display-linear observer light as a camera signal. QuickTime's Apple video-gamma interpretation then diverged in shadows, contrast and colour density. V38 derives an inverse-BT.1886 professional master and an sRGB Mac companion from the same Lobs. JPEG and web inherit only the companion. P3 and HDR are not used as unmeasured colour or brightness controls.</p><pre><code>{deliveryCode}</code></pre><div className="equation"><span>DELIVERY INVARIANT</span><b>EOTF<sub>BT.1886</sub>(V<sub>master</sub>) ≈ EOTF<sub>sRGB</sub>(V<sub>Mac</sub>) ≈ L<sub>obs</sub></b><small>Across three native 24-frame scenes, mean per-channel disagreement after both 12-bit ProRes files decode to light is 0.009–0.062%.</small></div></div></section>

      <section className="method-section"><div className="method-index">V37</div><div className="method-copy"><span className="section-tag">INDEPENDENT SITES · STABLE INTEGRATION</span><h2>Every film frame renews; the imaging operator should not jump as one field</h2><p>V36 emulsion sites were already independent on every frame, but each record and speed population also drew one whole-field subpixel phase, rotating the bilinear integration kernel from frame to frame. V37 keeps frame in the Philox identity and fixes the 15 size-class phases as a golden-ratio ensemble rotated by 30 degrees. Grain is neither smoothed, motion-following nor frozen; only the extra numerical breathing is removed.</p><pre><code>{stablePhaseCode}</code></pre><div className="equation"><span>TEMPORAL BOUNDARY</span><b>G<sub>t</sub> ⟂ G<sub>t+1</sub>　·　K<sub>integration,t</sub>=K<sub>integration</sub></b><small>Stochastic emulsion remains independent; the transfer of the integration operator stays stable.</small></div></div></section>

      <section className="method-section"><div className="method-index">V35</div><div className="method-copy"><span className="section-tag">AUDITABLE PRODUCTION GRAPH</span><h2>The realization may be independent; every identity must remain traceable</h2><p>Production need not reproduce the exact V34 PCG64 grain mosaic, but it must preserve the finite-binomial distribution, 48 µm RMS, NPS, layer statistics and temporal independence. V35 compares complete Philox uint32 words with a 2^32 fixed-point threshold derived from float32 probability. Frame, record, speed population, size class and global pixel coordinates define identity. Asynchronous Metal overlaps CPU expectation filtering; all 45 calls per frame are deduplicated and persisted in provenance.</p><pre><code>{productionCode}</code></pre><div className="equation"><span>PROBABILITY BOUNDARY</span><b>|p<sub>u32</sub>−p<sub>float32</sub>| &lt; 2<sup>−32</sup></b><small>The observed three-source maximum is 2.269e-10; V34 remains the byte-exact Archive reference.</small></div></div></section>

      <section className="method-section"><div className="method-index">V34</div><div className="method-copy"><span className="section-tag">PROCESSED MTF · SINGLE GENERATION</span><h2>Compute the total response once; encode the result once</h2><p>Kodak's 5279 MTF is measured on processed film and already contains the mid-frequency rise from developer adjacency. V34 retains that total MTF and disables the later duplicate deterministic intralayer DIR term. Interimage transport and stochastic grain coupling remain in development space. Both observers then complete the V31 colour boundary in linear Rec.709 before their sole delivery encode.</p><div className="equation"><span>DETERMINISTIC STRUCTURE</span><b>MTF<sub>out</sub>=MTF<sub>Kodak, ECN-2</sub></b><small>No second DIR-acutance response is multiplied in.</small></div><div className="equation"><span>SINGLE-GENERATION OUTPUT</span><b>Proj<sub>master</sub>=Encode(A(Proj<sub>lin</sub>,Scan<sub>lin</sub>))</b><small>The scan master is Encode(Scanlin); there is no intermediate ProRes round trip.</small></div></div></section>

      <section className="method-section"><div className="method-index">00</div><div className="method-copy"><span className="section-tag">V33 · INPUT / TONE / DELIVERY CONTRACT</span><h2>Separate camera witness, film exposure and technical neutralization</h2><p>T002, T007 and T031 use one frozen film model. The camera witness is fixed at 0.00 stop, film input is explicitly +0.45 stop, and Technical Neutral is disabled. The validator measures native 12-bit 1-1-1, display black, toe, p05–p95 contrast, a 32-bin monotonic tone curve and effective log-luma power.</p><div className="equation"><span>EXPOSURE BOUNDARY</span><b>Camera=V709(RAW)　·　Film=5279(RAW·2<sup>0.45</sup>)</b><small>If a gray card authorizes WB/tint correction, it belongs before 5279.</small></div><div className="equation"><span>BLACK GATE</span><b>Black = fraction(Y′<sub>709</sub> ≤ 1/1023)</b><small>Black, toe and gamma are reported separately instead of collapsing into a subjective “richer” judgement.</small></div></div></section>

      <section className="method-section"><div className="method-index">01</div><div className="method-copy"><span className="section-tag">V28 · RAW INPUT CONTRACT</span><h2>Decoded linear BT.2020 becomes three film records</h2><p>AVFoundation delivers demosaiced, white-balanced RGB tagged extended-linear BT.2020/D65—not Bayer values awaiting a second Camera LUT. V28 performs only a linear BT.2020→XYZ D65→V-Gamut primary conversion, with no repeated white balance or nonlinear camera separation.</p><div className="equation"><span>INPUT PRIMARIES</span><b>RGB<sub>V-Gamut</sub> = M<sub>XYZ→V</sub> · M<sub>2020→XYZ</sub> · RGB<sub>decoded</sub></b><small>All matrices operate in linear light; V-Log is not the ProRes RAW decode curve.</small></div><div className="equation"><span>RECORD EXPOSURE</span><b>E<sub>c</sub>(x,y) = Σ<sub>j</sub>M<sub>cj</sub>RGB<sub>j</sub>(x,y)</b></div><div className="equation"><span>NEGATIVE DENSITY</span><b>D<sub>c</sub> = H<sub>c</sub>(log<sub>10</sub>E<sub>c</sub>)</b><small>Each Hc samples the published 5279 Status-M characteristic curve.</small></div></div></section>

      <section className="method-section"><div className="method-index">02</div><div className="method-copy"><span className="section-tag">FINITE SITES</span><h2>Fast, medium and slow populations</h2><p>Every colour record contains three overlapping speed populations. A logistic transition defines the probability that a site develops. Binomial sampling makes variance fall naturally at both unexposed and fully developed extremes.</p><div className="equation"><span>ACTIVATION</span><b>p<sub>c,k</sub> = σ((logE<sub>c</sub> − μ<sub>c,k</sub>) / w<sub>c</sub>)</b></div><pre><code>{siteCode}</code></pre></div></section>

      <section className="method-section"><div className="method-index">03</div><div className="method-copy"><span className="section-tag">DYE-CLOUD SPECTRUM</span><h2>Grain is a multi-scale optical integral of finite events</h2><p>Each speed population is represented by five cloud-size classes. V26 gives fast, medium and slow populations different class weights, so exposure selects a spatial spectrum. Every record/exposure is then renormalized to Kodak’s published 48 µm RMS.</p><div className="equation"><span>DENSITY NPS</span><b>NPS<sub>c</sub>(f|E) = Σ<sub>k</sub>p<sub>c,k</sub>(1−p<sub>c,k</sub>)|H<sub>c,k</sub>(f)|²</b></div></div></section>

      <section className="method-section"><div className="method-index">04</div><div className="method-copy"><span className="section-tag">DEVELOPMENT DIR</span><h2>Reaction–diffusion happens before record densities are merged</h2><p>Nine sub-emulsions release bounded inhibitor fields at their own lateral scales. A finite transport matrix moves those fields to receiver layers and affects both deterministic density and stochastic deviations.</p><pre><code>{dirCode}</code></pre></div></section>

      <section className="method-section"><div className="method-index">05</div><div className="method-copy"><span className="section-tag">SPECTRAL NEGATIVE</span><h2>Dye formation includes the coloured mask</h2><p>The three records are not ideal CMY. Signed net spectral curves combine newly formed dye with consumed masking couplers. The print path retains the full D-min/orange-base spectrum; the scan performs its own film match.</p><div className="equation"><span>NEGATIVE TRANSMISSION</span><b>T<sub>neg</sub>(λ)=10<sup>−[Dmin(λ)+Σa<sub>c</sub>ΔD<sub>c,net</sub>(λ)]</sup></b></div></div></section>

      <section className="method-section"><div className="method-index">06</div><div className="method-copy"><span className="section-tag">2383 ANALYTICAL DYES</span><h2>Integral Status-A density is inverted before it becomes dye amount</h2><p>The model numerically inverts 2383 principal curves into analytical cyan, magenta and yellow dye amounts, applies LAD-centred print interimage, then integrates the resulting transmission under the xenon/CIE observer.</p></div></section>

      <section className="method-section split-method"><div className="method-index">07</div><div className="method-copy"><span className="section-tag">TWO OUTPUTS</span><h2>One negative, two observation chains</h2><div className="method-branches"><article><b>5279 → 2383 → xenon</b><p>A 3200 K printer light exposes three 2383 records. Print sensitometry, analytical dyes, print MTF/grain, Callier effect and projection flare belong only to this branch.</p></article><article><b>5279 → Period 2K → Cineon</b><p>Broad period RGB responses integrate negative transmission, followed by film matching, a 2K aperture, Cineon 0.002 D/code and restrained SDR finishing.</p><pre><code>{scanCode}</code></pre></article></div></div></section>

      <section className="method-section"><div className="method-index">08</div><div className="method-copy"><span className="section-tag">V30 · OFFICIAL LAD COLOUR ANCHOR</span><h2>Kodak channel densities anchor 2383—not a vendor LUT</h2><p>V30 replaces the simplified equal-density print neutral with H-61B’s official 1.09/1.06/1.03 D aims. The vendor D60 LUT and digitized dye-curve residuals remain in the research record, but their final hue and saturation weights are zero because they are not measured Kodak material evidence.</p><div className="equation"><span>OFFICIAL LAD / EVIDENCE WEIGHTS</span><b>D<sub>LAD</sub>=[1.09,1.06,1.03]　·　w<sub>D60</sub>=w<sub>hue</sub>=w<sub>sat</sub>=0</b></div></div></section>

      <section className="method-section"><div className="method-index">08B</div><div className="method-copy"><span className="section-tag">V31 · NORMAL-PROCESS CHROMA / TONE DECOUPLING</span><h2>2383 may reshape lightness without mistaking dye colour for silver</h2><p>V30 expressed chroma as C/L and then replaced L with the steeper 2383 neutral curve. Darker regions consequently lost absolute chroma; combined with full luminance texture, the result approached retained silver. V31 separates frequency after both complete observers: Period 2K supplies low-frequency OKLab a/b dye colour, 2383 retains its high-frequency opponent texture, and V30 per-pixel linear luma remains exact. Normal ECN-2/ECP-2D removes the silver image, so this is a process-boundary correction—not a saturation grade.</p><div className="equation"><span>FINAL OBSERVER BOUNDARY</span><b>ab<sub>out</sub>=G<sub>σ</sub>＊ab<sub>scan</sub>+[ab<sub>proj</sub>−G<sub>σ</sub>＊ab<sub>proj</sub>]　·　Y<sub>out</sub>=Y<sub>proj</sub></b><small>σ=0.72 px at 2K; gamut is compressed around target Y. 5279, print black, gamma and grain formation remain unchanged.</small></div></div></section>

      <section className="method-section"><div className="method-index">09</div><div className="method-copy"><span className="section-tag">COLOUR-GRAIN SEPARATION</span><h2>The observer integrates grain without regrading mean colour</h2><p>Signed grain delta is split into Rec.709 luminance and opponent components. Observer-specific integration affects only the opponent texture; deterministic mean RGB never enters this operation.</p><div className="equation"><span>SIGNED GRAIN</span><b>δY = wᵀδRGB　·　δC = δRGB − δY</b></div></div></section>

      <section className="method-section"><div className="method-index">10</div><div className="method-copy"><span className="section-tag">V38 · OUTPUT STANDARD</span><h2>Observer conditions, display light and file transfer are separate boundaries</h2><p>The 48-nit cinema condition remains in the 2383 observer and the period finish remains in the scan observer. Their output is display-linear Rec.709 light. The professional file uses inverse BT.1886 gamma 2.4; the direct-view companion for the Mac default display mode uses sRGB. In the XDR HDTV Video reference mode, judge the professional master.</p><pre><code>{deliveryCode}</code></pre></div></section>

      <section className="method-section"><div className="method-index">11</div><div className="method-copy"><span className="section-tag">EXACT ACCELERATION</span><h2>Cache deterministic colour; parallelize independent silver-halide events</h2><p>A 193³ lattice caches exact analytical print samples. Fixed seeded row stripes parallelize 45 binomial populations while remaining bit-identical across worker counts. Mean negative density is shared rather than recomputed.</p></div></section>

      <section className="method-section"><div className="method-index">12</div><div className="method-copy"><span className="section-tag">V27 · SCAN GRAY AXIS</span><h2>Level-dependent scanner balance with an exact luma lock</h2><p>The V26 period scan was neutral only at its 18% anchor. V27 renders a dense neutral exposure scale, derives a smooth RGB balance over display level and applies it only to the finished scan. The output is then renormalized to the original per-pixel Rec.709 luminance.</p><pre><code>{neutralCode}</code></pre><div className="equation"><span>INVARIANT</span><b>Y<sub>V27</sub>(x,y) = Y<sub>V26</sub>(x,y)</b><small>Black, lower-scale gamma, contrast and the 2K aperture cannot change through this operation.</small></div></div></section>

      <section className="method-section"><div className="method-index">13</div><div className="method-copy"><span className="section-tag">EVIDENCE BOUNDARY</span><h2>Negative findings are part of the algorithm</h2><p>The latest hourly audit found no public, stock-specific 5279 NPS, no measured 5279 DIR matrix and no 5279 parameter payload in the official JVT packages or the complete certified April 2003 provisional. That provisional names 5279; H022 switches the same identifier to 5218; the later patent returns to 5279. This proves document-branch drift, not a hidden measurement. V27 therefore changes none of those parameters.</p></div></section>

      <section className="validation"><span className="section-tag">V38 THREE-SCENE VALIDATION</span><h2>Shared release gates</h2><div className="validation-grid"><div><b>Native resolution</b><p>3 × 24 frames · 5760×4320</p></div><div><b>Dual 12-bit delivery</b><p>BT.1886 master + sRGB companion</p></div><div><b>Image model</b><p>V37 frozen in full</p></div><div><b>Temporal structure</b><p>Independent sites · stable integration</p></div><div><b>Web first frame</b><p>Same frame 12 as JPEG</p></div><div><b>Display target</b><p>Explicit; never guessed by the player</p></div></div></section>
    </main>
  );
}
