"use client";

import { SiteFooter, SiteHeader } from "../components/SiteHeader";
import { references } from "../data";
import { useLanguage } from "../i18n";
import { withBasePath } from "../basePath";
import { ResearchEnglish } from "./ResearchEnglish";

function Cite({ ids }: { ids: string[] }) { return <sup className="cite">{ids.map((id) => <a key={id} href={`#ref-${id}`}>{id.slice(1)}</a>)}</sup>; }

export default function ResearchPage() {
  const { language } = useLanguage();
  if (language === "en") return <><SiteHeader /><ResearchEnglish /><SiteFooter /></>;
  return (
    <>
      <SiteHeader />
      <main className="paper-page wrap">
        <header className="paper-header"><span className="eyebrow">RESEARCH NOTE · REVISION 2026.08 · V29</span><h1>从银盐位点到电影画面：<br />5279数码乳剂重建研究</h1><p className="abstract"><b>摘要</b>　本项目尝试从数码RAW重建Kodak VISION 500T 5279的成像过程，而不是复刻一组静态LUT。模型覆盖有限感光位点、彩色染料云、分层速度、DIR层间效应、5279光谱遮罩、2383分析染料与时期2K扫描；V29在V28正确RAW输入契约上完成165帧全运动验证，并把公开证据无法识别的NPS、DIR矩阵、三层配方与Spirit光谱明确锁定，不以单一场景的主观观感替代测量。</p><div className="paper-byline"><span>持续研究记录</span><span>方法 · 实验 · 错误复盘</span></div></header>

        <div className="paper-layout">
          <aside className="paper-toc"><b>目录</b><a href="#premise">1　研究命题</a><a href="#layers">2　多层乳剂</a><a href="#grain">3　颗粒与染料云</a><a href="#mask">4　有色遮罩</a><a href="#dir">5　DIR层间效应</a><a href="#scanner">6　扫描器耦合</a><a href="#black">7　黑位与高光</a><a href="#v21">8　V21基线</a><a href="#v22">9　V22结果</a><a href="#v23">10　V23结果</a><a href="#v24">11　V24结果</a><a href="#v25-plan">12　V25标准化</a><a href="#v26">13　V26曝光颗粒</a><a href="#v27">14　V27扫描灰轴</a><a href="#v28">15　V28 RAW输入</a><a href="#v29">16　V29完整运动</a><a href="#evidence-audit">17　证据审计</a><a href="#limitations">18　边界</a><a href="#references">引用</a></aside>
          <article className="paper-body">
            <section id="premise"><div className="section-tag">01 · PREMISE</div><h2>研究命题</h2><p>数码相机先形成规则像素采样，噪声通常被视作需要移除或后加的信号扰动。胶片的微观随机性发生得更早：光子是否使某个卤化银晶体形成可显影潜影，会决定随后是否生成染料。因此“颗粒”与图像密度并不是两个完全独立的对象。<Cite ids={["R2", "R3", "R13"]} /></p><blockquote>画面不是先存在，再长出颗粒；画面密度就是大量离散显影事件经过光学观察后的统计结果。</blockquote><p>这不意味着数码无法逼近胶片。关键是不要在显示空间模拟表面噪声，而要在曝光和显影域重新采样有限事件，再让印片或扫描器观察它们。</p><blockquote>Baseline只描述胶片、印片与扫描链本身；“更好看”的艺术选择不写进“更准确”的成像模型。</blockquote><p>因此模型不会为某一帧加入讨喜的lift、饱和度或风格曲线。创作调色应当发生在可复现baseline之外，让同一底层模型能支持更多电影、摄影机与审美方向。</p></section>

            <section id="layers"><div className="section-tag">02 · LAYERS</div><h2>一条颜色记录内部仍有多个速度层</h2><p>彩色负片至少包含蓝、绿、红感光记录，分别生成黄、品红、青染料。每条记录又可以由快、中、慢乳剂组成，以覆盖暗部、中间调和高光。较快群体通常依赖更大的有效晶体，较慢群体更细密；三者的显影区间彼此重叠。<Cite ids={["R2", "R7", "R15"]} /></p><div className="layer-diagram" aria-label="乳剂层示意"><div className="coat">保护层 / UV</div><div className="blue"><b>蓝感记录</b><span>快 · 中 · 慢 → 黄染料</span></div><div className="filter">黄色滤光层</div><div className="green"><b>绿感记录</b><span>快 · 中 · 慢 → 品红染料</span></div><div className="inter">中间层 / 清除剂</div><div className="red"><b>红感记录</b><span>快 · 中 · 慢 → 青染料</span></div><div className="base">片基 + rem-jet</div></div><p>V14—V20让三个颜色记录共用一套代表性粒径。V21已把这种自由度放开：青记录快／中／慢有效云约1.28／0.83／0.58µm，品红约1.36／0.79／0.52µm，黄约1.14／0.88／0.68µm；这些并非宣称5279秘方，而是由同期Kodak结构给出形态先验，再整体回标5279公开的R/G/B 48µm RMS颗粒和MTF。<Cite ids={["R1", "R7", "R11"]} /></p></section>

            <section id="grain"><div className="section-tag">03 · GRAIN</div><h2>最终看到的是染料云，不是留下的银影</h2><p>曝光后的卤化银被彩色显影剂还原成金属银；显影剂同时氧化并与成色剂反应，在同一位置生成不溶染料。随后漂白把金属银转回银盐，定影将银盐移走。处理完成的彩色负片留下的是染料图像和过程存留的有色遮罩。<Cite ids={["R2", "R3", "R15"]} /></p><div className="process-strip"><span>曝光</span><i>→</i><span>潜影位点</span><i>→</i><span>银显影 + 染料生成</span><i>→</i><span>漂白 / 定影移银</span><i>→</i><b>染料云图像</b></div><p>因此“银盐沸腾感”更准确的算法表达，是每一帧重新采样受曝光约束的有限显影位点；染料云的大小、重叠、亚像素位置和光学积分决定可见颗粒。随机样本改变，条件均值必须不漂移。</p><div className="equation"><span>有限位点</span><b>Var(f) = p(1 − p) / n</b><small>未曝光时p≈0、完全显影时p≈1，方差都下降；转换区间最大。</small></div></section>

            <section id="mask"><div className="section-tag">04 · MASK</div><h2>橙色底是局部颜色校正留下的常数项</h2><p>真实青、品红染料存在不希望的旁带吸收。红感层中的品红色遮罩耦合剂会在生成青染料时被消耗；青染料增加造成的绿/蓝旁带吸收，与品红耦合剂减少造成的密度下降在波段平均上互相补偿。绿感层的黄色遮罩耦合剂执行类似功能。<Cite ids={["R1", "R2", "R3"]} /></p><p>所以5279数据表中“D-mins subtracted”的染料曲线是净密度变化：新染料吸收加上遮罩耦合剂被消耗的反向变化。局部负值具有物理意义。把它裁成正值，或在光谱染料之外再加一遍橙色遮罩，都会造成明显色偏。</p><div className="equation"><span>净光谱密度</span><b>ΔD<sub>net</sub>(λ) = D<sub>dye</sub>(λ) − D<sub>mask consumed</sub>(λ)</b><small>形状不可能逐波长完美抵消；残余光谱误差构成片种色彩性格。</small></div></section>

            <section id="dir"><div className="section-tag">05 · DIR</div><h2>DIR把局部清晰度和饱和度变成同一个化学问题</h2><p>显影抑制剂释放型成色剂会在显影处释放抑制剂。抑制剂既能在本层扩散形成边缘邻接效应，提高中频MTF；也能迁移到相邻颜色记录，改变中性曝光和颜色分离曝光之间的gamma关系。中间层、清除剂和带电聚合物会限制或反射这种迁移。<Cite ids={["R6", "R11"]} /></p><p>这意味着饱和度不是全局HSV旋钮。Kodak同期实验用“颜色分离曝光gamma / 中性曝光gamma”衡量层间色彩效应；同一种DIR在不同层位可以增加或降低饱和度。</p><div className="equation"><span>颜色分离饱和度指标</span><b>S<sub>c</sub> ≈ γ<sub>separation,c</sub> / γ<sub>neutral,c</sub></b><small>它随颜色、曝光、邻域和层位置变化。</small></div><p>V21已将DIR移入显影域：每个快／中／慢群体先生成不同扩散尺度的局部抑制场，通过有界层间传输矩阵影响接收群体，最后才合并密度。均匀曝光的局部差分严格为零，因此重排后中性H-D最大偏差只有约2.4×10⁻⁷ D。</p></section>

            <section id="scanner"><div className="section-tag">06 · SCANNER</div><h2>Status-M测量器不等于时期Telecine</h2><p>5279数据表的H-D和颗粒是Status-M测量结果；真正的Telecine拥有自己的光源、滤光器和探测器响应。Kodak 1994年的扫描相关专利指出，典型Telecine红通道在远离青染料峰值的位置读数，同时会接收到品红染料长波尾部。结果是红调制不足、串色，并需要电子增益，进一步放大噪声。<Cite ids={["R11", "R12"]} /></p><p>更重要的是，Kodak会直接改变负片红记录相对绿记录的反差，使Telecine在独立通道校正之前就接近R/G反差一致。底片与扫描器从设计阶段已经耦合。</p><div className="observer-grid"><div><b>Status-M</b><span>窄带标准密度</span><small>只用于匹配数据表</small></div><div><b>Period 2K</b><span>宽带探测器 + 光学film match</span><small>形成DI / Cineon</small></div><div><b>2383 Print</b><span>印片灯 + 正片感色层</span><small>形成放映正片</small></div></div><p>《霹雳娇娃2》使用5279负片、2K数字中间片并由EFILM完成后期，是极有价值的2003完成态参考。但它还包含创作调色、2K系统限制和后来家庭媒体转换，因此不能直接当作未调色的5279测量。<Cite ids={["R9", "R10"]} /></p></section>

            <section id="black"><div className="section-tag">07 · TONE</div><h2>黑位、高光、颗粒和曲线斜率必须一起校准</h2><p>降低整体负片反差可以减少扫描噪声，却也可能让中间调发平，并不能自动改善暗部可见性。同期Kodak实验通过改变toe与中段斜率的比例，在较低测量噪声下保持中间调并改善阴影细节。<Cite ids={["R12"]} /></p><p>放映黑由2383最大密度、投影杂散光和银幕亮度共同限定；蓝光黑是扫描、Cineon映射、显示OETF和母版黑锚点的共同决定。两者不能通过同一条lift/gamma/gain曲线互相追平。</p></section>

            <section id="v21"><div className="section-tag">08 · V21 RESULT</div><h2>从可验证目标到正式母版</h2><ol className="research-plan"><li><b>中性轴不漂移</b><span>显影域DIR重排后的H-D最大绝对误差约2.4×10⁻⁷ D。</span></li><li><b>颜色记录独立形态</b><span>青、品红、黄记录分别使用自己的快／中／慢云尺寸、光学扩散和位点数。</span></li><li><b>48µm颗粒回标</b><span>三记录在测试曝光范围内的RMS误差约0–1.5%，没有用“更有机”作为增大噪点的借口。</span></li><li><b>三个观察器</b><span>Status-M只解数据表轴；宽带Period 2K负责扫描；5279透射光、印片灯和2383感色层负责放映。</span></li><li><b>修复V20假差异</b><span>V20的显示适配从扫描分支继承了约92%色相与94%饱和度，所以截图主要只剩黑位差；V21只共享中性明度目标。</span></li><li><b>双母版</b><span>两条链都从同一段GH7 ProRes RAW输出5760×4320、12-bit ProRes 4444。</span></li></ol></section>

            <section id="v22"><div className="section-tag">09 · V22 · ANALYTICAL DYE</div><h2>V21的颜色问题不是“调得不够”，而是密度含义用错了</h2><p>2383数据表的Status-A曲线表示观察器对多种染料共同吸收后的积分密度，不等于三个互不串扰的CMY染料量。V21把这些积分值再次乘以染料光谱，重复计算了旁带吸收。Kodak的分析染料方法要求从积分密度反解各染料贡献；同期电影色彩研究也表明，5279→2383的全量程不能由一个3×3矩阵完整描述。<Cite ids={["R16", "R17", "R20"]} /></p><div className="equation"><span>分析染料反演</span><b>D<sub>A</sub> = F(a<sub>C</sub>,a<sub>M</sub>,a<sub>Y</sub>)　⇒　a = F<sup>−1</sup>(D<sub>A</sub>)</b><small>F包含光谱透射、Status-A权重和对数积分，因此必须非线性求逆。</small></div><p>V22随后在LAD附近施加层间印片曝光矩阵，再进入2383主曲线。物理投影转成Rec.709仍不唯一，因此显示器预览参考公开2383 D60变换，但只采用“彩色输入相对同码值中性输入”的Oklab a/b差值，不采用其绝对白点。<Cite ids={["R5", "R18", "R19"]} /></p><ol className="research-plan"><li><b>被证伪：手动减弱层间矩阵</b><span>0/25/50/75/100%保持测试中，完整强度最好；没有为主观观感删除耦合。</span></li><li><b>被拒绝：13项三次多项式</b><span>它无法保留真实帧上的非线性色度校正，最终保留25³相对色度格点。</span></li><li><b>六色保持</b><span>相对七套完成态厂商变换，中位色相误差由7.94°降至1.46°，最大值由14.62°降至6.90°；六个饱和度幅度全部位于厂商包络内。</span></li><li><b>真实帧A/B</b><span>落在Resolve D55–D65色相包络内的像素由20.2%增至45.9%；色相与色度联合命中由10.9%增至34.8%。</span></li><li><b>黑位与高光</b><span>生产12-bit链没有通道在1.0裁切；亮度p99.99约0.958、最大约0.987。V22与V21的中位亮度差仅0.0016，变化主要来自颜色而非对比。</span></li><li><b>双母版</b><span>放映和扫描使用同一段6帧、同一份5279乳剂随机实现，均为5760×4320、12-bit ProRes 4444。</span></li></ol></section>

            <section id="v23"><div className="section-tag">10 · V23 · ORGANIC DYE-CLOUD FIELD</div><h2>更有机，不等于更粗或更响</h2><p>Kodak把彩色负片影像描述为在卤化银位点周围形成的大量染料云，并以48µm孔径的扩散RMS评价宏观颗粒；它约束可见幅度，却不公开5279每种染料云的完整尺寸概率分布。同期多层专利说明不同速度群体会使用不同颗粒尺度。V23因此只改变形态先验，不改变公开幅度目标。<Cite ids={["R1", "R7", "R21"]} /></p><div className="equation"><span>五点尺寸分布近似</span><b>r = [0.62, 0.78, 0.98, 1.22, 1.55] · r<sub>c,k</sub></b><small>权重为[0.10, 0.24, 0.34, 0.22, 0.10]；加权中心约为1，最终仍回标48µm RMS。</small></div><p>独立的摄影染料影像研究测得近似1/f型噪声功率谱，这支持加入温和的多尺度相关尾部，但该实验对象是反转片，不是5279负片，所以V23只把它当作形态先验。Kodak自己的染料扩散专利还警告：染料云过度扩散可能让RMS数值变好，却增加低频Wiener能量和视觉大斑块。V23因此把最大云限制在10%，并降低整体相关尺度，不追求夸张1/f。<Cite ids={["R22", "R23"]} /></p><p>另一项为电子扫描设计的Kodak负片专利说明，最高速层常减少成色剂量以限制刚离开D-min区域的颗粒贡献，还可让同一颜色记录的不同速度层形成可区分的染料波段。它不是5279配方，但支持“暗部彩噪必须在分层染料形成中处理”的方向；V23保留V20起的曝光相关染料贡献模型，不凭该专利发明5279的具体分层光谱。<Cite ids={["R24"]} /></p><ol className="research-plan"><li><b>颜色泛化</b><span>T020的树皮、蘑菇、亮叶和天空，以及T032的雨天青绿与暗柱均未出现新裁切或饱和度越界。</span></li><li><b>被拒绝：三白点色度格点</b><span>D55/D60/D65中位相对色度模型与V22 D60结果实质相同；没有可测收益，因此不作为V23颜色变化。</span></li><li><b>颗粒连续性</b><span>三尺寸改为五点分布，亚像素方向采用2.399963弧度黄金角步进，相关尺度0.88→0.86；孤立密度峰值在T020测试帧下降约16%。</span></li><li><b>测量守恒</b><span>均匀曝光测试的48µm RMS最大相对误差约0.5–1.3%，逐帧平均密度漂移低于约0.00038D。</span></li><li><b>安全加速</b><span>完整分析放映链在193³密度格点上精确求样；真实帧99%像素Oklab ΔE低于约0.36，逐像素放映映射约快14倍。</span></li><li><b>一秒验证母版</b><span>两段各24帧、1.001秒；放映与扫描共享同一份逐帧5279随机实现，均为5760×4320、12-bit ProRes 4444。并行计算到第24帧的总等待约59分11.5秒。</span></li></ol></section>

            <section id="v24"><div className="section-tag">11 · V24 · 35MM SPECTRAL SEPARATION</div><h2>V23像早期CCD，并不是一种错觉</h2><p>V23同时保留了三个容易被人眼识别为早期数码的线索：较多大尺度染料云、较高的综合色颗粒，以及原始数码素材的高微反差。Kodak称5279为细颗粒、高锐度片种，但48µm扩散RMS只是在指定孔径下测得的幅度，不是完整噪声功率谱。Kodak的Print Grain Index方法进一步指出，最终颗粒还取决于负片的颗粒频率分布、放大倍率、印片材料反差、负片与正片MTF以及印片系统MTF。因此同样的48µm RMS可以呈现出非常不同的8/16/35mm观感。<Cite ids={["R1", "R4", "R21", "R22", "R25"]} /></p><div className="equation"><span>观察到的颗粒频谱</span><b>NPS<sub>out</sub>(f) ≈ NPS<sub>neg</sub>(f)|MTF<sub>chain</sub>(f)|² + NPS<sub>print/scan</sub>(f)</b><small>放大倍率把胶片上的空间频率映射到银幕；RMS是积分结果，无法反推出唯一的NPS形状。</small></div><p>V24首先把五级尺寸权重从[.10,.24,.34,.22,.10]改为[.16,.30,.32,.17,.05]，相关尺度0.86降到0.76；较大云的尾部被削弱，但每条记录仍重新回标5279公开的48µm RMS。随后只把输出RGB颗粒分解为明度分量与综合色分量：明度颗粒原样保留，综合色部分在2383观看链和Period 2K扫描链中分别进行亚像素积分。这个步骤不接触确定性平均画面，所以色相、饱和度、黑位和曲线不会跟着偷偷变化。<Cite ids={["R4", "R8", "R23"]} /></p><div className="equation"><span>综合色颗粒分离</span><b>δY = wᵀδRGB　·　δC = δRGB − δY</b><small>V24只对δC执行观察器积分并降低强度；δY以及mean RGB完整保留。</small></div><ol className="research-plan"><li><b>平均颜色锁定</b><span>两个真实场景中，V24与V23确定性平均输出的最大绝对RGB差均为0.000000。</span></li><li><b>综合色识别线索下降</b><span>T020放映综合色/明度颗粒比约1.58→0.93，扫描约1.72→0.92；T032约2.07→1.15与2.11→1.08。</span></li><li><b>官方RMS继续成立</b><span>三个测试曝光、三条记录在48µm孔径下的最大相对误差约0.6–1.4%。</span></li><li><b>保留有机运动</b><span>逐帧有限位点、五级云群、DIR随机耦合、负片和正片颗粒均未冻结；变化不是静态降噪。</span></li><li><b>有意没有做</b><span>V24不重新设计黑白灰或创作调色。这样用户看到的差异能归因于颗粒频谱，而不是一条更讨喜的曲线。</span></li></ol><p><b>性能剖析：</b>两段各1.001秒双母版的并行总等待约58分32秒。逐阶段计时显示，乳剂随机形成约77.5秒/帧，是最大成本；现场调用栈主要停在45组全画幅NumPy二项采样。16核机器采样时仍约80% CPU空闲，解码约1秒/帧、双路编码不足0.5秒/帧，因此当前速度主要受参考实现未并行化限制，不是ProRes、磁盘或硬件能力不足。</p></section>

            <section id="v25-plan"><div className="section-tag">12 · V25 RESULT · COLOUR PIPELINE + EXACT ACCELERATION</div><h2>观看条件不是源文件函数；速度来自删除重复工作</h2><p>第一次V25把“显示器怎样发光”误当成“母版怎样编码”：蓝光分支直接写入BT.1886反函数，2383监看分支又被转成P3 gamma 2.6。播放器仍按Rec.709解释文件，因此T020蓝光首帧平均码值由V24的1060升到1355，暗部低值由304升到557。用户看到的提亮和色彩变浅是真实的管线错误，不是5279颜色变化。<Cite ids={["R26", "R27", "R31"]} /></p><div className="equation"><span>ITU-R BT.1886</span><b>L = a·max(V+b, 0)<sup>2.4</sup></b><small>这是参考显示EOTF。它约束显示端V→L，不要求把其反函数直接当作Rec.709交换母版的源文件OETF。</small></div><p>修正版保留两个已经完成的Rec.709监看观察器：2383分支内部仍模拟48 cd/m²、gamma 2.6影院观看，再适配到监视器；2K DI分支仍以BT.1886作为蓝光参考显示条件。两份ProRes交换母版统一使用Rec.709 OETF与完整1-1-1标记，网页再明确解码Rec.709并编码为sRGB。Adobe RGB不进入电影主链。<Cite ids={["R28", "R29", "R30", "R32"]} /></p><div className="equation"><span>端到端分离</span><b>film observer → Rec.709 OETF / 1-1-1 → reference display　|　sRGB proxy</b><small>影院gamma与BT.1886属于观察器；源文件、显示器和网页不再互相冒充。</small></div><ol className="research-plan"><li><b>亮度回归</b><span>T020蓝光单帧YAVG由错误版1354.7回到1060.24；V24基线为1060.04。YLOW由557回到304，与V24一致。</span></li><li><b>完整元数据回读</b><span>放映监看与蓝光ProRes均为5760×4320、12-bit 4:4:4、Rec.709 1-1-1；不再使用播放器容易误解的P3/ST 428混合ProRes标签。</span></li><li><b>全画幅线程一致</b><span>45组银盐二项抽样改为固定种子行条带；5760×4320下1线程与8线程数组完全相同，max Δ=0，抽样阶段70.09→35.22秒。</span></li><li><b>删除重复显影</b><span>V24每帧在平均分支与颗粒函数内计算两次确定性负片密度；V25复用同一数组，数学结果逐像素不变。</span></li><li><b>没有质量捷径</b><span>分辨率、24帧长度、45组颗粒、RMS回标、MTF、DIR、2383与扫描器全部保留；输出修正不重新调5279颜色。</span></li><li><b>Hourly审计</b><span>V22分析染料/层间矩阵是已通过真实色块与实拍保持测试的结论，继续保留；toe、单点LAD、窄带Spirit、DLE绿通道和rem-jet残余候选因不可识别或泛化失败不进入V25。</span></li></ol></section>

            <section id="v26"><div className="section-tag">13 · V26 · EXPOSURE-CONDITIONED GRAIN NPS</div><h2>35mm的细腻，不等于所有亮度共用一张细噪点</h2><p>Kodak的电影胶片参考明确说明：高速、较敏感的晶体通常最大；在阴影或欠曝光区域，最快、最大的晶体贡献占优，所以颗粒感更明显。同期多层专利进一步给出每条颜色记录至少可由快、中、慢层叠置的结构，并以速度差换取感光度与颗粒度的平衡。公开5279数据却只给总记录的H-D、MTF和48µm扩散RMS，不披露每一亚层的完整粒径分布。<Cite ids={["R1", "R7", "R21", "R33"]} /></p><p>V21已经让快／中／慢层拥有不同基础云半径，但V25仍让三个速度层共用同一套五级尺寸权重。V26只放开这个维度：快层权重为[.12,.26,.34,.20,.08]，中层沿用[.16,.30,.32,.17,.05]，慢层变为[.22,.34,.29,.12,.03]。每行总和为1，且三记录在每个曝光下继续回标官方48µm RMS；因此总“响度”、均值颜色、黑白灰、MTF、DIR、2383与扫描完成曲线不变。</p><div className="equation"><span>曝光相关颗粒频谱</span><b>NPS<sub>c</sub>(f|E) = Σ<sub>k∈fast,mid,slow</sub> p<sub>c,k</sub>(E)[1−p<sub>c,k</sub>(E)] · |H<sub>c,k</sub>(f)|²</b><small>再以5279公开σ<sub>48µm,c</sub>(E)归一；曝光决定谁贡献频谱，官方RMS决定总积分振幅。</small></div><div className="diagnostic-grid"><figure><img src={withBasePath("/research/v26-grain-nps.png")} alt="V25与V26在阴影、中间调和高光的归一化径向颗粒噪声功率谱" /><figcaption>绿记录归一化径向NPS：变化刻意克制，阴影稍向低频、高光向更细尺度移动。</figcaption></figure><figure><img src={withBasePath("/research/v26-layer-variance-activation.png")} alt="快中慢三速度层随曝光变化的局部二项方差贡献" /><figcaption>曝光通过p(1−p)选择不同速度层，而不是事后按亮度给噪点调强弱。</figcaption></figure></div><ol className="research-plan"><li><b>空间验证</b><span>阴影样本中快层约贡献61–65%颗粒功率；高光中慢层约贡献50–59%。三个颜色记录都显示同方向变化。</span></li><li><b>时间验证</b><span>四帧均匀曝光、三记录的最大绝对lag-1相关约0.0074，平均绝对相关约0.0028；不是固定纹理的移动或循环。</span></li><li><b>均值守恒</b><span>均匀场最大平均密度漂移约0.00015D；T020/T032蓝光首帧YAVG相对V25只变化0.09/0.10个12-bit码值，YLOW仍为304/281。</span></li><li><b>正式效率</b><span>T020为31分34.14秒，T032为31分33.93秒；两段并行总等待31分34秒。97%以上核心时间位于浮点负片、随机乳剂与观察器，编解码不是瓶颈。</span></li><li><b>插件准备</b><span>本机Resolve 2026 OpenFX SDK已验证float RGBA及Metal/CUDA/OpenCL入口。迁移方案以Metal为首个目标，使用绝对像素坐标的counter-based随机数保证分块、线程与重渲染不改变颗粒。</span></li><li><b>有意没有做</b><span>没有加入更讨喜的饱和度、对比度、lift或锐度，也没有提高颗粒幅度。V26只检验乳剂形态。</span></li><li><b>证据边界</b><span>三套权重是由Kodak机制、5279公开RMS与保守NPS约束出的模型选择，不是宣称复原未公开涂布配方。</span></li></ol></section>

            <section id="v27"><div className="section-tag">14 · V27 · DENSITY-DEPENDENT SCAN NEUTRALITY</div><h2>绿色薄雾不是5279色彩，而是扫描观察器的灰轴误差</h2><p>V26的Period 2K分支只在18%灰和一个高密度点上校准RGB平衡，并人为保留18%的扫描器／染料残余。实拍中性暗部因此出现绿色隆起，中灰锚点正确，亮部偏移方向又改变。这个形状说明它不是一项全局白平衡问题；用固定品红修正会同时破坏真实植物绿色与高光。V27以2049级中性场景曝光贯穿5279显影、Period 2K孔径、Cineon与蓝光完成链，得到随输出亮度变化的RGB平衡函数。</p><div className="equation"><span>灰轴校正与亮度守恒</span><b>RGB′ = C(Y)⊙RGB · Y / (wᵀ[C(Y)⊙RGB])</b><small>C(Y)来自完整中性曝光尺度；w为Rec.709亮度权重。校正只改变扫描RGB比例，不改变每像素亮度。</small></div><div className="diagnostic-grid"><figure><img src={withBasePath("/research/v27-scan-neutral-axis.png")} alt="V26和V27扫描灰轴残差随亮度变化的对比" /><figcaption>2049级中性曝光诊断：V27压低阴影与低中间调的绿色对手残差，同时保持亮度轴。</figcaption></figure></div><ol className="research-plan"><li><b>灰轴残差</b><span>最大通道残差由0.01820降至0.00236，95百分位由0.01673降至0.00166。</span></li><li><b>绿色对手轴</b><span>最大|G−(R+B)/2|由0.02172降至0.00242。</span></li><li><b>亮度、黑位与Gamma</b><span>逐像素Rec.709亮度最大漂移低于1.8×10⁻⁷；因此这不是提亮、压黑或重新调对比。</span></li><li><b>放映分支</b><span>V27的2383母版直接复用V26并校验逐字节一致，扫描修复不会污染放映颜色。</span></li><li><b>拒绝的方案</b><span>把Period 2K原色校正强度从0.82直接推到1.0会让实拍画面更绿、更亮，已被A/B测试拒绝。</span></li><li><b>Hourly证据边界</b><span>最新官方文件审计确认：DIR扩散因子依赖具体化合物，48µm RMS不能唯一反推NPS，官方测试材料中的stock/model编号也不是5279参数表。新找到的2003年4月临时专利原件确实把identifier 3写成5279，但同年5月H022改成5218、后续专利又回到5279；它证明文档分支沿革，不提供任何频谱、协方差或颗粒参数。V27因此不改V26颗粒、DIR或染料模型。<Cite ids={["R34", "R35", "R36", "R37", "R38", "R39", "R40", "R41"]} /></span></li></ol></section>

            <section id="v28"><div className="section-tag">15 · V28 · PRORES RAW INPUT CONTRACT</div><h2>第二层绿色来自错误的Camera LUT阶段，而不是胶片</h2><p>V27修正了扫描器整条灰阶的RGB中性，但两条观察链仍共享一种更早发生的颜色偏移。解码器请求128-bit RGBA float后，Core Video附件明确把缓冲标为extended-linear BT.2020/D65。V27却先把这些值编码成V-Log，再应用Panasonic的RAW-Gamut→V-Gamut Camera LUT；这等于把已经完成一次标准RAW转换的BT.2020原色再次当成尚未分离的RAW Gamut。<Cite ids={["R44", "R45", "R46", "R47"]} /></p><div className="equation"><span>V28输入变换</span><b>RGB<sub>V-Gamut</sub> = M<sub>XYZ→V-Gamut</sub> · M<sub>BT.2020→XYZ</sub> · RGB<sub>Apple linear</sub></b><small>矩阵之间没有V-Log编码；保留AVFoundation标准转换与as-shot元数据，不加入第二次白平衡。</small></div><ol className="research-plan"><li><b>不是减绿色调色</b><span>不修改lift、gamma、gain、饱和度或色温；只纠正输入原色与Camera LUT的阶段契约。</span></li><li><b>双场景泛化</b><span>T020扫描近中性G/R由1.04294降至1.02895；T032由1.06476降至1.04777。T032仍保持真实雨天青绿。</span></li><li><b>放映也必须重算</b><span>错误发生在5279曝光之前，因此2383与扫描版都从同一份V28负片重新形成，不能复用V27放映结果。</span></li><li><b>色调边界</b><span>p99–p99.9亮度基本不变，没有新白场裁切；合成均匀灰在完整链中保持中性。</span></li><li><b>胶片锁定</b><span>5279 H-D、光谱染料、DIR、颗粒NPS、MTF、2383、Spirit、黑位和Gamma全部保持V27。</span></li><li><b>质量无损加速</b><span>193³ 2383分析格点经过SHA-256校验；新旧采样器导出的两条12-bit视频解码RGB48哈希逐位一致。</span></li></ol></section>

            <section id="v29"><div className="section-tag">16 · V29 · FULL-MOTION VALIDATION</div><h2>最后15–20%不能靠继续调味完成</h2><p>H-1-5279t直接约束中性H-D、MTF与48µm孔径下的分记录RMS；它没有公布频率分辨NPS、三层真实配方、5279专属DIR矩阵或Spirit私有光谱。V29因此不修改V28画面形成参数，而把剩余可实现部分转成完整运动与交付验证。<Cite ids={["R1", "R7", "R8", "R21", "R22", "R34", "R35", "R36", "R37"]} /></p><div className="equation"><span>有限位点与RMS约束</span><b>Var(p̂)=p(1−p)/N　　D<sub>formed</sub>=D<sub>mean</sub>+δD·σ<sub>5279</sub>(logE)/σ<sub>pred</sub>(logE)</b><small>48µm RMS确定孔径积分后的幅度，却不能唯一反演二维颗粒频谱。</small></div><ol className="research-plan"><li><b>165帧全长</b><span>T002的每一帧都通过5279负片、2383与Period 2K观察器。</span></li><li><b>绝对帧种子</b><span>并行区段按源帧号形成新乳剂；接缝不重置、不循环、不平移颗粒贴图。</span></li><li><b>真实运动门槛</b><span>逐帧检查黑场、高光裁切、高频RMS和相邻帧相关性；它是场景压力测试，不冒充5279实测NPS。</span></li><li><b>段边界逐位验证</b><span>完整母版第82帧与独立第82帧解码RGB48完全相等。</span></li><li><b>验证结果</b><span>165/165帧通过；两观察器的全运动白场硬截断均为0，音频、时间码与Rec.709 1-1-1标记完整。</span></li><li><b>计算效率</b><span>两支原分辨率母版并行总耗时3113.17秒（51分53.17秒），即每源帧18.87秒。</span></li><li><b>下一证据</b><span>真正替换剩余先验需要同批5279/GH7色卡与分色阶梯、ECN-2控制和高分辨率扫描。</span></li></ol></section>

            <section id="evidence-audit"><div className="section-tag">15 · EVIDENCE AUDIT · 10 NOTES</div><h2>十份小时研究笔记，真正改变的是证据边界</h2><p>截至2026年8月4日，小时研究已暂停。十份独立笔记逐项审计了DIR、ECN-2控制实验、颗粒测量、JVT文件沿革与专利档案路线；它们没有产出可直接写入5279模型的新参数，因此V27生产基线保持不变。</p><div className="evidence-ledger"><article className="evidence-group"><span className="evidence-state confirmed">已证实</span><h3>公开文件能支持什么</h3><ul><li>Kodak的DIR扩散因子是具体化合物的测定指标，不是5279固定的层间常数。</li><li>ECN-2绿光单色曝光是排除路径的因果控制，不是可移植的层间系数。</li><li>2003年4月临时专利把identifier 3写成5279；5月JVT-H022则写成5218，文档分支确实发生漂移。</li><li>US 7,899,113所在专利族于2016年末由Thomson转让给Dolby。<Cite ids={["R34", "R35", "R38", "R39", "R41", "R43"]} /></li></ul></article><article className="evidence-group"><span className="evidence-state denied">已否证</span><h3>不能据此声称什么</h3><ul><li>H-24过程控制的警戒／行动限不是测量不确定度。</li><li>一个或有限个48µm孔径RMS不能非参数地反推出连续NPS。</li><li>5279型号名或JVT model_id不等于公开参数表、LUT或颗粒频谱。</li><li>专利权继受不证明实验邮件、LUT或实验室记录也被移交。<Cite ids={["R36", "R37", "R38", "R40", "R43"]} /></li></ul></article><article className="evidence-group"><span className="evidence-state unknown">仍未知</span><h3>公开档案仍未回答</h3><ul><li>5279实际DIR化合物、位置、反应—扩散动力学与跨层矩阵。</li><li>完整的5279 NPS、快／中／慢亚层粒径分布及物理尺度。</li><li>JVT示例在2003年4月至5月由5279改为5218的原因。</li><li>现有公开JVT邮件证据止于2002年；Dolby是否保管PU030116工作档案尚无证据。<Cite ids={["R42", "R43"]} /></li></ul></article></div><blockquote>审计结论不是“没有进展”，而是把不能识别的参数留在假设层，避免把专利示例、控制限或编号沿革误写成5279配方。</blockquote><p><b>未来可证伪路径：</b>若能获得频率分辨的5279颗粒测量、同批次中性／分色ECN-2密度对、或PU030116同期带测量元数据的原始附件，才可分别检验NPS形状、层间响应与JVT型号映射；在此之前不调整生产参数。</p></section>

            <section id="limitations"><div className="section-tag">16 · LIMITS</div><h2>我们知道什么，也明确不知道什么</h2><ul><li><b>直接知道：</b>5279公开的曲线、RMS颗粒、MTF、感色和净染料密度。</li><li><b>机制上知道：</b>Kodak同期多层乳剂、DIR、遮罩、Telecine补偿和ECN-2过程。</li><li><b>仍在推断：</b>5279每一亚层的真实晶体与染料云尺寸分布、完整Wiener/NPS曲线、涂布量、DIR化合物、扩散常数，以及影院→Rec.709的唯一观看适配。</li><li><b>无法由RGB恢复：</b>原始场景的连续光谱、镜头内部光谱透过率和真实化学批次。</li></ul><p>网站中所有推断都会保留来源等级。模型追求的是受测量约束的物理近似，不宣称破解Kodak未公开配方。</p></section>
          </article>
        </div>

        <section id="references" className="references"><div className="section-tag">REFERENCES</div><h2>引用与资料</h2><ol>{references.map((ref) => <li id={`ref-${ref.id}`} key={ref.id}><span>{ref.id.slice(1).padStart(2, "0")}</span><div><a href={ref.url} target="_blank" rel="noreferrer">{ref.title}</a><small>{ref.type}</small></div></li>)}</ol></section>
      </main>
      <SiteFooter />
    </>
  );
}
