import { references } from "../data";

function Cite({ ids }: { ids: string[] }) { return <sup className="cite">{ids.map((id) => <a key={id} href={`#ref-${id}`}>{id.slice(1)}</a>)}</sup>; }

function referenceTypeEnglish(type: string) {
  const translated = type
    .replace(/Kodak片种数据|Kodak正片数据/g, "Kodak stock data")
    .replace(/Kodak技术读物|Kodak电影胶片参考指南/g, "Kodak technical guide")
    .replace(/Kodak处理规范|Kodak实验室控制|Kodak技术资料/g, "Kodak process / technical publication")
    .replace(/Eastman Kodak专利/g, "Eastman Kodak patent")
    .replace(/Adobe Systems专利/g, "Adobe Systems patent")
    .replace(/同期后期制作报道/g, "Period post-production report")
    .replace(/完成态参考/g, "Finished-state reference")
    .replace(/扫描器资料/g, "Scanner documentation")
    .replace(/官方标准|标准|规范/g, "Official standard")
    .replace(/研究/g, "Research")
    .replace(/实验逻辑/g, "Experimental method")
    .replace(/测量机制/g, "Measurement mechanism")
    .replace(/非5279配方|不是5279配方|不是5279常数|不是5279参数/g, "not a 5279 formula or parameter")
    .replace(/[（）]/g, (mark) => mark === "（" ? " (" : ")");
  return /\p{Script=Han}/u.test(translated) ? "Primary / technical source" : translated;
}

export function ResearchEnglish() {
  return (
    <main className="paper-page wrap">
      <header className="paper-header"><span className="eyebrow">RESEARCH NOTE · REVISION 2026.08 · V28</span><h1>From silver-halide sites<br />to a motion-picture image</h1><p className="abstract"><b>Abstract</b> — This project reconstructs Kodak VISION 500T 5279 image formation from digital RAW rather than copying a static LUT. It models finite sensitive sites, dye clouds, speed layers, DIR interimage effects, the coloured negative mask, Kodak 2383 print formation and a period 2K scan. V28 corrects the mistaken reinterpretation of AVFoundation's converted linear-BT.2020 buffer as Panasonic RAW Gamut while retaining every V27 film, grain, tone and observer parameter.</p><div className="paper-byline"><span>LIVING RESEARCH RECORD</span><span>METHOD · EXPERIMENT · ERROR REVIEW</span></div></header>

      <div className="paper-layout">
        <aside className="paper-toc"><b>CONTENTS</b><a href="#premise">1　Premise</a><a href="#layers">2　Layered emulsion</a><a href="#grain">3　Grain and dye clouds</a><a href="#mask">4　Coloured mask</a><a href="#dir">5　DIR interimage</a><a href="#scanner">6　Scanner coupling</a><a href="#tone">7　Black and highlights</a><a href="#v21-en">8　V21 structure</a><a href="#v22-en">9　V22 colour</a><a href="#v23-en">10　V23 morphology</a><a href="#v24-en">11　V24 35 mm spectrum</a><a href="#v25-en">12　V25 output standard</a><a href="#v26-en">13　V26 grain NPS</a><a href="#v27">14　V27 scan calibration</a><a href="#v28-en">15　V28 RAW input</a><a href="#evidence-audit-en">16　Evidence audit</a><a href="#limits-en">17　Limits</a><a href="#references">References</a></aside>
        <article className="paper-body">
          <section id="premise"><div className="section-tag">01 · PREMISE</div><h2>The image does not exist first and acquire grain later</h2><p>Digital noise is usually treated as a disturbance added to a regular pixel sample. Film randomness occurs earlier: whether photons create a developable latent image in a finite silver-halide crystal determines whether dye will form at that location. Density and grain are therefore two observations of the same population of events.<Cite ids={["R2", "R3", "R13"]} /></p><blockquote>Image density is the optical observation of many discrete development events.</blockquote><p>The baseline reconstructs film, print and scan behaviour. Lift, saturation and aesthetic contrast remain external creative decisions.</p></section>

          <section id="layers"><div className="section-tag">02 · LAYERS</div><h2>Each colour record contains more than one speed layer</h2><p>Blue-, green- and red-sensitive records form yellow, magenta and cyan dyes. Within every record, overlapping fast, medium and slow emulsions trade sensitivity for granularity. Faster populations usually require larger effective crystals and dominate low exposure; slower, finer populations increasingly carry highlights.<Cite ids={["R2", "R7", "R15"]} /></p><div className="layer-diagram" aria-label="Simplified emulsion stack"><div className="coat">Protective / UV layer</div><div className="blue"><b>Blue-sensitive record</b><span>fast · medium · slow → yellow dye</span></div><div className="filter">Yellow filter layer</div><div className="green"><b>Green-sensitive record</b><span>fast · medium · slow → magenta dye</span></div><div className="inter">Interlayer / scavenger</div><div className="red"><b>Red-sensitive record</b><span>fast · medium · slow → cyan dye</span></div><div className="base">Base + rem-jet</div></div><p>The record-specific sizes used by the model are same-era structural priors, not a claim to Kodak’s undisclosed 5279 coating. Final R/G/B amplitude and resolution are normalized to the published 48 µm RMS and MTF measurements.</p></section>

          <section id="grain"><div className="section-tag">03 · GRAIN</div><h2>The processed colour negative contains dye clouds, not retained silver</h2><p>Colour development reduces exposed halide to silver while oxidized developer forms insoluble dye. Bleach and fixer subsequently remove the silver image. Printing and scanning observe dye clouds and the retained coloured mask.<Cite ids={["R2", "R3", "R15"]} /></p><div className="process-strip"><span>Exposure</span><i>→</i><span>Latent sites</span><i>→</i><span>Silver development + dye formation</span><i>→</i><span>Bleach / fix</span><i>→</i><b>Dye-cloud image</b></div><div className="equation"><span>FINITE SITES</span><b>Var(f) = p(1 − p) / n</b><small>Variance falls when a population is almost unexposed or almost fully developed and peaks through its transition.</small></div></section>

          <section id="mask"><div className="section-tag">04 · MASK</div><h2>The orange base is the constant remainder of imagewise colour correction</h2><p>Real cyan and magenta dyes have unwanted side absorptions. Coloured masking couplers are consumed in the opposite direction during dye formation, approximately flattening those absorptions across a band. The 5279 data-sheet curves marked “D-mins subtracted” are signed net-density changes, not isolated positive dye spectra.<Cite ids={["R1", "R2", "R3"]} /></p><div className="equation"><span>NET SPECTRAL DENSITY</span><b>ΔD<sub>net</sub>(λ) = D<sub>dye</sub>(λ) − D<sub>mask consumed</sub>(λ)</b><small>Residual mismatch after band-average correction contributes to a stock’s colour character.</small></div></section>

          <section id="dir"><div className="section-tag">05 · DIR</div><h2>Local sharpness and saturation share one chemical mechanism</h2><p>Development-inhibitor-releasing couplers emit inhibitors where development occurs. Lateral transport can create adjacency and acutance; transport into neighbouring records changes the relationship between neutral and separation exposure. Layer placement, barriers, scavengers and release timing all matter.<Cite ids={["R6", "R11"]} /></p><div className="equation"><span>SEPARATION INDEX</span><b>S<sub>c</sub> ≈ γ<sub>separation,c</sub> / γ<sub>neutral,c</sub></b><small>Saturation is record-, exposure-, neighbourhood- and layer-dependent—not a global HSV knob.</small></div><p>The current matrix is a bounded phenomenological model. Hourly research found that Kodak’s published DIR diffusion-factor assay is compound-specific and cannot be reinterpreted as a measured 5279 3×3 coefficient.</p></section>

          <section id="scanner"><div className="section-tag">06 · SCANNER</div><h2>A Status-M densitometer is not a period telecine</h2><p>Status-M defines the measurement axis for sensitometry and granularity. A telecine has its own lamp, filters, broad detector responses, film matching and electronic primary correction. Same-era Kodak work documents red-channel dye cross-talk and film designs pre-compensated for electronic transfer.<Cite ids={["R11", "R12"]} /></p><div className="observer-grid"><div><b>Status-M</b><span>NARROW STANDARD DENSITY</span><small>Data-sheet measurement only</small></div><div><b>Period 2K</b><span>BROAD DETECTORS + FILM MATCH</span><small>DI / Cineon result</small></div><div><b>2383 print</b><span>PRINTER LIGHT + PRINT RECORDS</span><small>Projection positive</small></div></div><p><i>Charlie’s Angels: Full Throttle</i> is a valuable 2003 finished-state reference because it used 5279 and a 2K DI, but its creative grade, post pipeline and later home-video transfer are not bare-stock measurements.<Cite ids={["R9", "R10"]} /></p></section>

          <section id="tone"><div className="section-tag">07 · TONE</div><h2>Black, highlights, grain and curve slope must be calibrated together</h2><p>Projection black is limited by 2383 maximum density, projector/room flare and screen luminance. Blu-ray black is created by scan density, Cineon mapping, signal transfer and display behaviour. One lift/gamma/gain curve cannot make these distinct chains physically identical.</p></section>

          <section id="v21-en"><div className="section-tag">08 · V21</div><h2>Development, structure and observers move into their proper domains</h2><ol className="research-plan"><li><b>Neutral invariance</b><span>Population-domain DIR vanishes on a uniform field; H-D drift fell to roughly 2.4×10⁻⁷ D.</span></li><li><b>Record-specific morphology</b><span>Cyan-, magenta- and yellow-forming records receive different fast/mid/slow cloud scales and site counts.</span></li><li><b>Three observers</b><span>Status-M measures; a broad period observer scans; 5279 transmission and 2383 form the print.</span></li></ol></section>

          <section id="v22-en"><div className="section-tag">09 · V22 · ANALYTICAL DYES</div><h2>Status-A density cannot be reused as dye amount</h2><p>Status-A integrates overlapping print-dye absorption under standard weights. V22 numerically inverts principal curves to analytical dye amounts, applies print interimage around LAD and then forms 2383 density. A neutral-subtracted D60 vendor target contributes relative OKLab a/b only, never an absolute tint.<Cite ids={["R16", "R17", "R18", "R19", "R20"]} /></p></section>

          <section id="v23-en"><div className="section-tag">10 · V23 · DYE-CLOUD FIELD</div><h2>More organic does not mean coarser or louder</h2><p>Five size classes, golden-angle subpixel phases and a restrained large-cloud tail approximate a continuous dye-cloud population while every record remains normalized to the published 48 µm RMS. T020 and T032 provide cross-scene RAW holdouts.<Cite ids={["R1", "R7", "R21", "R22", "R23", "R24"]} /></p></section>

          <section id="v24-en"><div className="section-tag">11 · V24 · 35 MM SPECTRAL SEPARATION</div><h2>Why V23 could still resemble early CCD or 16 mm</h2><p>Gauge appearance depends on magnification, low-frequency power and the complete negative/print/scan MTF—not only one aperture RMS number. V24 shifts cloud power to finer scales and integrates opponent-colour grain separately in projection and scan observers while preserving luminance grain and deterministic RGB.<Cite ids={["R1", "R4", "R21", "R22", "R25"]} /></p><div className="equation"><span>OBSERVED GRAIN</span><b>NPS<sub>out</sub>(f) ≈ NPS<sub>neg</sub>(f)|MTF<sub>chain</sub>(f)|² + NPS<sub>print/scan</sub>(f)</b></div></section>

          <section id="v25-en"><div className="section-tag">12 · V25 · OUTPUT STANDARD</div><h2>Viewing conditions are not source-file transfer functions</h2><p>The first V25 export incorrectly baked inverse display EOTFs into Rec.709-tagged files. The corrected release delivers both monitor masters with Rec.709 OETF and complete 1-1-1 metadata. Gamma 2.6 remains inside the cinema observer; BT.1886 remains a reference-display EOTF; web proxies explicitly convert decoded Rec.709 light to sRGB.<Cite ids={["R26", "R27", "R28", "R29", "R30", "R31", "R32"]} /></p></section>

          <section id="v26-en"><div className="section-tag">13 · V26 · EXPOSURE-CONDITIONED GRAIN NPS</div><h2>Fine 35 mm grain does not use one texture at every exposure</h2><p>Fast, medium and slow populations receive distinct five-class cloud distributions. Exposure determines which population supplies local variance; the published 5279 RMS determines the integrated amplitude. Colour, tone, MTF, DIR and both observers remained V25.</p><div className="diagnostic-grid"><figure><img src="/research/v26-grain-nps.png" alt="V25 and V26 normalized radial grain spectra" /><figcaption>Normalized green-record NPS: shadows move slightly lower in frequency while highlights become finer.</figcaption></figure><figure><img src="/research/v26-layer-variance-activation.png" alt="Fast medium and slow variance contribution over exposure" /><figcaption>p(1−p) selects speed layers through exposure rather than changing post-noise strength.</figcaption></figure></div></section>

          <section id="v27"><div className="section-tag">14 · V27 · PERIOD-SCAN NEUTRAL SCALE</div><h2>The green veil was a real density-dependent scanner calibration error</h2><p>V26 balanced the period scan at 18% gray and one high-density anchor while deliberately retaining 18% of an assumed scanner/dye residual. Neutral diagnostics showed a green hump in shadows and lower midtones, exact neutrality at the single 18% anchor, and a change of bias direction above mid-gray. The web Rec.709→sRGB path and V26 grain were not responsible.</p><div className="equation"><span>NEUTRAL-SCALE CONSTRAINT</span><b>RGB′(x) = C<sub>Y(x)</sub>[RGB(x)]　with　Y(RGB′) = Y(RGB)</b><small>A dense neutral scale supplies level-dependent RGB balance. Every pixel retains its incoming Rec.709 luminance, so the correction cannot become lift, contrast or gamma.</small></div><div className="diagnostic-grid"><figure><img src="/research/v27-scan-neutral-axis.png" alt="V26 and V27 period scan neutral-axis residual" /><figcaption>Maximum neutral channel residual fell from about 0.0182 to 0.00236; projection drift is exactly zero.</figcaption></figure></div><ol className="research-plan"><li><b>Green-opponent residual</b><span>Maximum magnitude fell from about 0.0217 to 0.00242 over display-linear Y 0.005–0.90.</span></li><li><b>Luminance preservation</b><span>Maximum numerical drift is below 1.8×10⁻⁷ before output encoding.</span></li><li><b>Projection lock</b><span>The 2383 projection result is numerically and byte-for-byte the V26 master.</span></li><li><b>Rejected alternative</b><span>Forcing complete primary separation made the real RAW frame greener and brighter, so it was not adopted.</span></li><li><b>Hourly boundary</b><span>The certified April 2003 provisional does name 5279 as identifier 3; May 2003 H022 substitutes 5218 and the later patent returns to 5279. This is document-branch drift, not a numerical calibration payload. No new 5279 NPS or DIR coefficient was recovered, so grain and chemistry remain V26.<Cite ids={["R38", "R39", "R41"]} /></span></li></ol></section>

          <section id="v28-en"><div className="section-tag">15 · V28 · PRORES RAW INPUT CONTRACT</div><h2>The second green veil came from a misplaced Camera LUT stage</h2><p>The decoder's Core Video attachments identify its float RGB buffer as extended-linear BT.2020/D65. V27 encoded that already converted RGB as V-Log and then applied Panasonic's RAW-Gamut-to-V-Gamut Camera LUT, effectively asking a nonlinear camera separation to interpret BT.2020 primaries as unseparated RAW Gamut.<Cite ids={["R44", "R45", "R46", "R47"]} /></p><div className="equation"><span>V28 INPUT TRANSFORM</span><b>RGB<sub>V-Gamut</sub> = M<sub>XYZ→V-Gamut</sub> · M<sub>BT.2020→XYZ</sub> · RGB<sub>Apple linear</sub></b><small>No V-Log transfer lies between the matrices, and no second white balance is introduced.</small></div><ol className="research-plan"><li><b>Not a minus-green grade</b><span>Lift, gamma, gain, saturation and colour temperature remain untouched.</span></li><li><b>Two-scene holdout</b><span>T020 scan near-neutral G/R falls from 1.04294 to 1.02895; T032 falls from 1.06476 to 1.04777 while retaining its genuine rainy cyan-green source colour.</span></li><li><b>Both observers recomputed</b><span>The error precedes 5279 exposure, so neither the print nor scan result can reuse V27 pixels.</span></li><li><b>Tone boundary</b><span>p99–p99.9 luminance is essentially unchanged, no new white clipping appears, and a synthetic uniform gray remains neutral.</span></li><li><b>Film lock</b><span>5279 sensitometry, dyes, DIR, grain NPS, MTF, 2383, Spirit, black and gamma remain V27.</span></li><li><b>Lossless acceleration</b><span>The 193³ analytical print lattice is hash-validated; decoded RGB48 hashes from both accelerated 12-bit masters are bit-identical to the reference path.</span></li></ol></section>

          <section id="evidence-audit-en"><div className="section-tag">15 · EVIDENCE AUDIT · 10 NOTES</div><h2>Ten hourly notes changed the evidence boundary—not the production model</h2><p>Hourly research was paused on 4 August 2026. Ten narrowly scoped notes audited DIR, ECN-2 controls, grain measurement, JVT document history and the patent-archive route. None supplied a new 5279 parameter that can be safely implemented, so the V27 production baseline remains unchanged.</p><div className="evidence-ledger"><article className="evidence-group"><span className="evidence-state confirmed">CONFIRMED</span><h3>What the records support</h3><ul><li>Kodak’s DIR diffusion factor is a compound assay, not a fixed 5279 cross-layer constant.</li><li>Green-only ECN-2 exposure is a causal exclusion control, not a transferable interimage coefficient.</li><li>The April 2003 provisional labels identifier 3 as 5279; May’s JVT-H022 labels it 5218. The document branch did drift.</li><li>The US 7,899,113 family was assigned by Thomson to Dolby effective at the end of 2016.<Cite ids={["R34", "R35", "R38", "R39", "R41", "R43"]} /></li></ul></article><article className="evidence-group"><span className="evidence-state denied">DISPROVED</span><h3>What cannot be claimed</h3><ul><li>H-24 process alarm/action limits are not measurement uncertainty.</li><li>One or finitely many 48 µm aperture RMS values cannot non-parametrically identify a continuous NPS.</li><li>A 5279 label or JVT model_id is not a published parameter table, LUT or grain spectrum.</li><li>Patent ownership does not establish custody of research mail, LUTs or lab records.<Cite ids={["R36", "R37", "R38", "R40", "R43"]} /></li></ul></article><article className="evidence-group"><span className="evidence-state unknown">UNKNOWN</span><h3>What public records still omit</h3><ul><li>The actual 5279 DIR compounds, placement, reaction–diffusion kinetics and cross-layer matrix.</li><li>A complete 5279 NPS, fast/mid/slow sublayer size distributions and physical scale.</li><li>Why the JVT example changed from 5279 to 5218 between April and May 2003.</li><li>The located public JVT mail evidence stops in 2002; Dolby custody of PU030116 working records is unproven.<Cite ids={["R42", "R43"]} /></li></ul></article></div><blockquote>The audit prevents patent examples, control limits and identifier history from being mistaken for a secret 5279 formula.</blockquote><p><b>Falsifiable next evidence:</b> frequency-resolved 5279 grain measurements, same-batch neutral/separation ECN-2 density pairs, or a contemporaneous PU030116 attachment with measurement metadata could test the NPS, interimage and stock-mapping hypotheses. Production parameters remain locked until such evidence exists.</p></section>

          <section id="limits-en"><div className="section-tag">16 · LIMITS</div><h2>What is known—and what remains unknowable</h2><ul><li><b>Direct:</b> published 5279 sensitometry, diffuse RMS granularity, MTF, sensitivity and net dye-density plots.</li><li><b>Mechanistic:</b> same-era Kodak multilayer, masking, DIR, ECN-2 and electronic-transfer documentation.</li><li><b>Still inferred:</b> actual 5279 per-sublayer size distributions, full Wiener/NPS curves, coating amounts, DIR compounds, diffusion constants and proprietary Spirit calibration.</li><li><b>Not recoverable from RGB:</b> original scene spectra, lens spectral transmission and chemical batch state.</li></ul><p>The model seeks a measurement-constrained physical approximation. It does not claim to recover Kodak’s undisclosed formula.</p></section>
        </article>
      </div>

      <section id="references" className="references"><div className="section-tag">REFERENCES</div><h2>Sources and citations</h2><ol>{references.map((ref) => <li id={`ref-${ref.id}`} key={ref.id}><span>{ref.id.slice(1).padStart(2, "0")}</span><div><a href={ref.url} target="_blank" rel="noreferrer">{ref.title}</a><small>{referenceTypeEnglish(ref.type)}</small></div></li>)}</ol></section>
    </main>
  );
}
